We want to train a model to predict an individual player's team statistics from a set group of 5 players. In otherwords, relative to an individual player's other 4 teammates, how well would that individual perform in a given season?

Our reference/baseline point will be the starting lineups for each team. 
For example:
The current projected starting lineup for the Lakers is currently Lonnie Walker, Patrick Beverley, Lebron James, Anthony Davis, and Damian Jones. Let's say we wanted to focus on Patrick Beverley's statistics. We can use his statistics with the team that season as a reference point for the model to try and find other players that average close to or similar stats as Patrick Beverley. We would want the model to predict stats with respect to the numbers that other players average as well. We know that Anthony Davis and Lebron James are high usage players, so any other player that accompany them will see a decrease in statistics. We expect bigger decreases for players that average more statistics and smaller decreases for players that average less statistics. Since Patrick Beverley is a guard, we would want to find guards that are simila

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_excel('nba_full.xlsx')

teams = list(df['team.abbreviation'].unique())

appended_data = []

#iterates through each team
for ind_team in teams:
    #name each team temp 
    temp = df.loc[df['team.abbreviation'] == ind_team]
    #calculate ind_team total minutes played
    temp['TmMP'] = temp['mpg'].sum()
    #calculate ind_team total fga
    temp['TmFGA'] = temp['fga'].sum()
    #calculate ind_team total fta
    temp['TmFTA'] = temp['fta'].sum()
    #calculate ind_team total turnover rate
    temp['TmTOV'] = temp['turnover'].sum()
    #calculate indiv player usage metric within ind_team... usage formula online
    temp['usage'] = 100 * ((temp['fga'] + 0.44 * temp['fta'] + temp['turnover']) * (temp['TmMP'] / 5)) / (temp['mpg'] * (temp['TmFGA'] + 0.44 * temp['TmFTA'] + temp['TmTOV']))
    print(ind_team)
    
    appended_data.append(temp)
    
    
appended_data = pd.concat(appended_data)

appended_data

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

MEM
MIA
MIL
CLE
MIN
CHI
TOR
PHX
DET
ORL
SAC
WAS
SAS
LAC
UTA
DAL
LAL
ATL
BOS
DEN
NYK
BKN
GSW
PHI
POR
OKC
HOU
NOP
CHA
IND

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
0,3,Steven,Adams,7,0,7.000000,C,265,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,26.100000,3.11,5.33,0.583,0.00,0.00,0.000,0.78,2.56,0.304,4.67,6.44,11.11,2.56,1.56,0.78,2.44,2.11,7.00,246.566667,96.39,25.22,15.32,13.179526
29,66,Dillon,Brooks,6,6,6.500000,G-F,220,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,17.766667,3.89,8.89,0.438,1.89,3.78,0.500,1.00,1.56,0.643,0.22,1.33,1.56,1.33,0.00,0.44,2.00,0.89,10.67,246.566667,96.39,25.22,15.32,23.655565
83,184,Danny,Green,6,6,6.500000,G-F,215,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,0.000000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,246.566667,96.39,25.22,15.32,NaN
114,231,Jaren,Jackson Jr.,6,11,6.916667,F-C,242,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,0.000000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,246.566667,96.39,25.22,15.32,NaN
122,249,Tyus,Jones,6,2,6.166667,G,196,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,24.000000,4.89,10.67,0.458,1.56,4.44,0.350,0.44,1.00,0.444,0.33,1.67,2.00,4.22,0.11,0.67,0.67,1.22,11.78,246.566667,96.39,25.22,15.32,20.629741
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,3130,Jalen,Smith,6,9,6.750000,F,215,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,24.000000,4.20,9.50,0.435,1.20,4.10,0.302,1.50,2.20,0.679,1.80,5.80,7.50,1.10,0.80,0.20,2.20,1.50,11.00,230.033333,87.33,22.74,15.75,20.287279
283,3131,Oshae,Brissett,6,7,6.580000,F,210,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,10.900000,0.90,2.40,0.368,0.40,1.50,0.250,0.60,0.80,0.833,0.60,1.00,1.60,0.40,0.00,0.30,0.50,0.50,2.80,230.033333,87.33,22.74,15.75,12.137731
284,3132,Isaiah,Jackson,6,9,6.750000,F,205,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,18.300000,3.20,5.20,0.618,0.00,0.10,0.000,1.90,2.80,0.676,1.50,3.50,5.10,1.20,1.40,0.50,2.60,1.20,8.40,230.033333,87.33,22.74,15.75,16.966831
285,3133,Aaron,Nesmith,6,5,6.420000,F,215,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,20.800000,2.40,6.30,0.386,1.00,3.40,0.290,1.00,1.20,0.818,0.30,2.80,3.10,1.60,0.80,0.30,2.60,1.00,6.90,230.033333,87.33,22.74,15.75,15.310908
286,3134,Goga,Bitadze,6,11,6.920000,C,250,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,13.100000,1.80,3.40,0.519,0.10,0.90,0.143,0.90,1.80,0.500,1.60,1.80,3.40,1.50,0.50,0.50,2.30,0.80,4.50,230.033333,87.33,22.74,15.75,15.503036

In [ ]:
appended_data = appended_data[appended_data["usage"] >= 0]

In [ ]:
appended_data.to_excel('nba_tidyfinal.xlsx')

In [ ]:
hawks = appended_data[appended_data["team.abbreviation"] == "ATL"]

In [ ]:
hawks

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
40,83,Clint,Capela,6,10,6.833333,C,240,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,27.216667,4.44,7.67,0.580,0.00,0.00,0.000,0.89,1.67,0.533,3.44,6.56,10.00,0.78,1.78,0.89,1.78,0.89,9.78,218.616667,85.21,19.07,11.37,14.224921
45,101,John,Collins,6,10,6.833333,F-C,235,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,33.000000,5.11,9.78,0.523,0.78,3.00,0.259,1.78,2.00,0.889,1.89,7.78,9.67,1.00,1.67,0.89,3.56,1.67,12.78,218.616667,85.21,19.07,11.37,15.563021
103,213,Aaron,Holiday,6,1,6.083333,G,185,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,19.100000,2.11,4.44,0.475,0.78,1.22,0.636,0.67,0.78,0.857,0.56,0.78,1.33,1.67,0.33,0.78,1.33,0.89,5.67,218.616667,85.21,19.07,11.37,12.371988
105,215,Justin,Holiday,6,6,6.500000,F-G,181,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,19.100000,2.22,6.11,0.364,1.22,4.22,0.289,0.00,0.00,0.000,0.00,0.78,0.78,1.56,0.33,0.44,2.11,0.22,5.67,218.616667,85.21,19.07,11.37,13.804323
126,252,Frank,Kaminsky,7,0,7.000000,F-C,242,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,1.100000,0.00,0.11,0.000,0.00,0.11,0.000,0.44,0.44,1.000,0.00,0.33,0.33,0.22,0.00,0.00,0.22,0.11,0.44,218.616667,85.21,19.07,11.37,15.661473
163,334,Dejounte,Murray,6,5,6.416667,G,170,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,37.000000,8.78,19.22,0.457,2.22,6.11,0.364,2.22,2.56,0.870,0.67,5.67,6.33,8.11,0.56,2.56,1.78,2.56,22.00,218.616667,85.21,19.07,11.37,25.786944
240,490,Trae,Young,6,2,6.166667,G,180,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,35.100000,8.67,22.78,0.380,2.44,8.00,0.306,8.44,9.22,0.916,0.89,2.44,3.33,9.44,0.22,0.67,1.78,3.33,28.22,218.616667,85.21,19.07,11.37,35.798669
247,3093,Onyeka,Okongwu,6,8,6.670000,F,240,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,19.800000,3.50,5.40,0.653,0.00,0.10,0.000,0.70,1.10,0.667,2.10,3.80,5.90,1.10,0.80,0.60,3.20,0.60,7.70,218.616667,85.21,19.07,11.37,13.640258
248,3094,AJ,Griffin,6,6,6.500000,F,222,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,13.400000,2.70,5.60,0.484,1.10,2.70,0.400,0.30,0.30,1.000,0.70,1.00,1.70,0.60,0.00,0.60,0.90,0.60,6.80,218.616667,85.21,19.07,11.37,19.682527
371,3218,Jalen,Johnson,6,8,6.670000,F,219,1,ATL,Atlanta,East,Southeast,Atlanta Hawks,Hawks,13.800000,1.80,4.10,0.435,0.20,1.40,0.143,0.70,1.00,0.667,0.50,2.70,3.20,0.70,0.30,0.70,1.40,0.50,4.50,218.616667,85.21,19.07,11.37,15.212346

Notes:
No notable anomalies for usage rate for the hawks.

In [ ]:
hornets = appended_data[appended_data["team.abbreviation"] == "CHA"]

In [ ]:
hornets

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
98,204,Gordon,Hayward,6,8,6.666667,F,225,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,24.7,5.0,10.6,0.472,1.0,2.8,0.357,2.9,3.7,0.784,0.4,3.0,3.4,3.3,0.2,0.6,0.6,2.2,13.9,243.9,97.9,22.2,16.3,22.984835
178,360,Kelly,Oubre Jr.,6,7,6.583333,F,205,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,29.2,6.3,15.1,0.417,2.7,7.3,0.370,2.1,3.2,0.656,0.8,3.5,4.3,1.2,0.3,1.3,3.0,1.1,17.4,243.9,97.9,22.2,16.3,23.727904
182,371,Mason,Plumlee,6,11,6.916667,F-C,235,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,24.7,3.2,5.4,0.593,0.0,0.0,0.000,1.9,3.5,0.543,2.5,5.6,8.1,4.0,0.6,0.4,3.4,1.7,8.3,243.9,97.9,22.2,16.3,13.764137
199,403,Terry,Rozier,6,1,6.083333,G,190,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,10.2,2.6,6.7,0.388,1.2,2.9,0.414,0.8,0.9,0.889,0.5,1.6,2.1,2.0,0.3,0.1,0.3,1.0,7.2,243.9,97.9,22.2,16.3,31.232197
211,421,Dennis,Smith Jr.,6,3,6.250000,G,195,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,28.4,4.5,9.2,0.489,0.9,2.1,0.429,0.5,0.9,0.556,0.6,3.2,3.8,5.8,0.5,2.1,2.1,1.8,10.4,243.9,97.9,22.2,16.3,15.789425
249,3095,Lamelo,Ball,6,7,6.580000,G,180,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,32.7,7.3,17.7,0.415,3.3,10.7,0.313,1.3,1.7,0.800,0.0,3.7,3.7,7.0,0.3,1.0,2.7,3.7,19.3,243.9,97.9,22.2,16.3,26.651335
250,3096,PJ,Washington,6,7,6.580000,F,230,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,31.8,5.6,13.2,0.427,1.8,5.3,0.333,2.1,2.7,0.791,1.2,3.3,4.5,1.9,1.0,0.6,2.8,1.7,15.1,243.9,97.9,22.2,16.3,19.907061
251,3097,James,Bouknight,6,4,6.330000,F,190,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,17.3,2.1,6.3,0.337,0.8,3.3,0.226,0.6,1.0,0.625,0.3,1.9,2.2,1.4,0.3,0.4,1.5,0.9,5.6,243.9,97.9,22.2,16.3,17.377186
252,3098,Jalen,McDaniels,6,9,6.750000,F,205,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,25.9,3.5,8.1,0.431,1.3,3.3,0.385,1.2,1.4,0.826,1.1,3.8,4.9,2.4,0.7,1.2,2.8,1.4,9.4,243.9,97.9,22.2,16.3,15.368846
253,3099,Nick,Richards,7,0,7.000000,C,245,4,CHA,Charlotte,East,Southeast,Charlotte Hornets,Hornets,19.0,3.6,5.6,0.640,0.0,0.0,0.000,2.4,3.2,0.745,2.9,2.9,5.8,0.8,0.8,0.1,2.1,0.8,9.5,243.9,97.9,22.2,16.3,16.170312

Note: Terry Rozier has a higher usage rate than Lamelo Ball, but this makes sense because Terry Rozier takes more shot attempts.

In [ ]:
heat = appended_data[appended_data["team.abbreviation"] == "MIA"]

In [ ]:
heat

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
1,4,Bam,Adebayo,6,10,6.833333,C-F,255,16,MIA,Miami,East,Southeast,Miami Heat,Heat,35.0,7.0,13.1,0.534,0.0,0.3,0.000,3.9,4.5,0.867,2.3,6.1,8.4,3.5,0.9,1.2,3.6,3.6,17.9,246.7,87.1,23.4,13.7,23.703340
38,79,Jimmy,Butler,6,8,6.666667,G-F,232,16,MIA,Miami,East,Southeast,Miami Heat,Heat,28.4,5.4,11.5,0.470,0.9,2.3,0.391,5.5,6.3,0.873,1.7,3.4,5.1,4.4,0.2,1.2,0.9,1.3,17.2,246.7,87.1,23.4,13.7,24.351559
55,120,Dewayne,Dedmon,7,0,7.000000,C,245,16,MIA,Miami,East,Southeast,Miami Heat,Heat,9.0,1.4,2.4,0.583,0.4,0.9,0.444,0.8,0.8,1.000,0.5,2.0,2.5,0.5,0.1,0.0,1.7,0.6,4.0,246.7,87.1,23.4,13.7,16.541018
97,203,Udonis,Haslem,6,8,6.666667,F,235,16,MIA,Miami,East,Southeast,Miami Heat,Heat,1.0,0.1,0.3,0.333,0.0,0.0,0.000,0.1,0.2,0.500,0.0,0.2,0.2,0.0,0.1,0.0,0.1,0.0,0.3,246.7,87.1,23.4,13.7,17.231872
143,286,Kyle,Lowry,6,1,6.083333,G,196,16,MIA,Miami,East,Southeast,Miami Heat,Heat,34.9,3.7,9.8,0.378,2.1,6.5,0.323,3.7,4.1,0.902,0.7,3.5,4.2,5.6,0.4,1.5,2.9,1.9,13.2,246.7,87.1,23.4,13.7,17.184533
195,397,Duncan,Robinson,6,8,6.666667,F,210,16,MIA,Miami,East,Southeast,Miami Heat,Heat,15.2,1.9,5.6,0.339,1.4,4.1,0.341,0.4,0.4,1.000,0.3,2.3,2.6,1.2,0.0,0.0,1.8,0.3,5.6,246.7,87.1,23.4,13.7,17.753129
246,3092,Haywood,Highsmith,6,7,6.583333,F,220,16,MIA,Miami,East,Southeast,Miami Heat,Heat,2.8,0.1,0.6,0.167,0.0,0.4,0.000,0.0,0.0,0.000,0.0,0.4,0.4,0.0,0.0,0.3,0.1,0.3,0.2,246.7,87.1,23.4,13.7,14.275299
254,3100,Tyler,Herro,6,5,6.420000,C,195,16,MIA,Miami,East,Southeast,Miami Heat,Heat,31.4,7.2,15.4,0.468,2.4,6.4,0.375,2.8,3.1,0.903,0.6,5.8,6.4,2.6,0.6,0.7,1.6,2.1,19.6,246.7,87.1,23.4,13.7,26.681170
255,3101,Caleb,Martin,6,5,6.420000,F,205,16,MIA,Miami,East,Southeast,Miami Heat,Heat,29.6,3.6,8.0,0.455,1.1,2.7,0.421,0.6,0.8,0.727,1.9,2.9,4.8,1.9,0.4,1.2,2.1,1.0,9.0,246.7,87.1,23.4,13.7,14.031804
256,3102,Gabe,Vicent,6,3,6.250000,G,200,16,MIA,Miami,East,Southeast,Miami Heat,Heat,26.3,3.6,8.7,0.415,1.6,4.9,0.324,1.4,1.7,0.840,0.3,2.0,2.3,3.1,0.1,0.9,2.7,1.5,10.2,246.7,87.1,23.4,13.7,18.487567
257,3103,Max,Strus,6,5,6.420000,G,215,16,MIA,Miami,East,Southeast,Miami Heat,Heat,33.1,5.4,11.7,0.460,3.0,7.9,0.378,1.3,1.5,0.864,0.7,3.1,3.8,1.8,0.4,0.9,2.4,1.1,15.1,246.7,87.1,23.4,13.7,18.060002

Note: Tyler Herro has a higher usage rate than Butler, but this makes sense since he takes more shot attempts.

In [ ]:
magic = appended_data[appended_data["team.abbreviation"] == "ORL"]

In [ ]:
magic

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
12,28,Mo,Bamba,7,0,7.000000,C,221,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,11.3,1.6,3.8,0.421,0.5,1.9,0.263,0.3,0.5,0.600,0.5,2.4,2.9,0.6,0.5,0.1,1.7,0.7,4.0,257.7,96.5,28.5,18.3,16.906088
41,85,Wendell,Carter Jr.,6,10,6.833333,F,255,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,33.4,5.5,10.8,0.509,1.0,3.3,0.303,4.0,4.9,0.816,2.2,7.2,9.4,3.0,0.4,0.8,3.6,2.3,16.0,257.7,96.5,28.5,18.3,18.487312
198,402,Terrence,Ross,6,7,6.583333,G-F,206,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,23.7,3.1,6.9,0.449,1.5,3.7,0.405,0.4,0.6,0.667,0.4,1.9,2.3,1.1,0.2,0.7,1.9,0.5,8.1,257.7,96.5,28.5,18.3,13.088405
258,3104,Bol,Bol,7,2,7.170000,C,220,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,24.7,5.1,8.1,0.623,0.8,1.9,0.414,1.7,1.9,0.862,1.6,6.3,7.9,0.7,2.0,0.2,1.6,2.2,12.6,257.7,96.5,28.5,18.3,18.247856
259,3105,Franz,Wagner,6,10,6.830000,F,220,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,34.1,7.5,15.3,0.487,0.9,3.6,0.259,2.7,3.2,0.854,1.1,3.2,4.3,4.4,0.3,0.7,2.3,2.7,18.6,257.7,96.5,28.5,18.3,23.035942
260,3106,Paolo,Banchero,6,10,6.830000,F,250,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,34.6,8.1,17.5,0.461,1.0,3.9,0.256,6.4,8.3,0.769,0.8,7.5,8.3,3.6,0.9,0.7,2.4,3.0,23.5,257.7,96.5,28.5,18.3,28.252480
261,3107,Cole,Anthony,6,3,6.250000,G,185,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,30.5,5.5,13.3,0.415,1.8,5.0,0.350,2.8,3.8,0.733,0.8,4.0,4.8,4.3,0.8,0.8,3.5,2.0,15.5,257.7,96.5,28.5,18.3,22.522301
372,3219,RJ,Hampton,6,6,6.500000,G,190,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,14.4,2.2,4.5,0.492,0.9,2.0,0.462,1.2,1.3,0.941,0.5,0.9,1.4,1.3,0.3,0.7,1.2,1.0,6.6,257.7,96.5,28.5,18.3,17.066672
373,3220,Chuma,Okeke,6,6,6.500000,F,229,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,21.7,2.0,5.1,0.395,1.1,3.5,0.327,0.9,1.1,0.765,1.3,3.1,4.4,1.5,0.5,0.5,1.9,0.6,6.0,257.7,96.5,28.5,18.3,11.534249
374,3221,Jalen,Suggs,6,5,6.420000,G,205,22,ORL,Orlando,East,Southeast,Orlando Magic,Magic,29.3,4.8,11.2,0.429,1.5,5.0,0.300,1.8,2.9,0.621,0.9,2.4,3.3,5.2,0.4,1.7,3.9,3.3,12.9,257.7,96.5,28.5,18.3,21.792590

Note: Nothing peculiar with the Magic with regards to usage rate.

In [ ]:
wizards = appended_data[appended_data["team.abbreviation"] == "WAS"]

In [ ]:
wizards

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
14,31,Will,Barton,6,6,6.500000,G,190,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,23.766667,3.33,8.11,0.411,1.56,3.67,0.424,0.89,1.00,0.889,0.22,2.44,2.67,2.33,0.22,0.78,1.44,1.22,9.11,243.65,87.05,23.17,13.47,18.093268
17,37,Bradley,Beal,6,5,6.416667,G,207,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,35.216667,8.22,15.78,0.521,1.44,4.44,0.325,3.67,4.00,0.917,0.67,2.89,3.56,5.67,0.78,0.89,2.00,2.67,21.56,243.65,87.05,23.17,13.47,25.258572
77,173,Taj,Gibson,6,9,6.750000,F,232,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,2.100000,0.44,0.89,0.500,0.11,0.33,0.333,0.44,0.44,1.000,0.00,0.44,0.44,0.00,0.00,0.00,0.22,0.00,1.44,243.65,87.05,23.17,13.47,22.711218
132,265,Kyle,Kuzma,6,9,6.750000,F,220,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,31.883333,6.11,13.44,0.455,2.00,5.67,0.353,3.22,4.11,0.784,0.67,6.44,7.11,2.22,0.67,0.22,3.22,1.67,17.44,243.65,87.05,23.17,13.47,23.355346
162,330,Monte,Morris,6,3,6.250000,G,175,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,27.100000,3.11,7.67,0.406,0.89,2.78,0.320,1.22,1.67,0.733,0.33,3.56,3.89,5.56,0.22,0.78,1.11,1.00,8.33,243.65,87.05,23.17,13.47,15.274641
187,378,Kristaps,Porzingis,7,3,7.250000,F-C,240,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,30.883333,7.11,14.00,0.508,1.89,5.00,0.378,4.11,4.89,0.841,2.56,6.11,8.67,2.11,1.11,0.67,3.33,1.67,20.22,243.65,87.05,23.17,13.47,25.398803
238,487,Delon,Wright,6,5,6.416667,G,183,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,10.100000,1.00,2.56,0.391,0.22,1.22,0.182,0.33,0.56,0.600,0.44,0.67,1.11,1.44,0.44,1.22,0.56,0.44,2.56,243.65,87.05,23.17,13.47,14.147229
262,3108,Deni,Avdija,6,9,6.750000,F,210,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,23.000000,2.50,6.50,0.388,0.90,2.60,0.333,1.30,1.60,0.792,0.80,3.70,4.50,1.90,0.70,0.60,3.10,1.40,7.20,243.65,87.05,23.17,13.47,16.465059
263,3109,Corey,Kispert,6,6,6.500000,F,224,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,22.400000,2.90,5.30,0.541,1.10,2.90,0.400,1.00,1.10,0.875,0.00,1.90,1.90,1.70,0.00,0.70,1.10,0.90,7.90,243.65,87.05,23.17,13.47,13.133460
264,3110,Rui,Hachimura,6,8,6.670000,F,230,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,23.100000,4.70,9.80,0.476,0.70,2.20,0.333,1.40,1.90,0.724,0.70,3.90,4.60,0.90,0.50,0.30,1.10,1.40,11.50,243.65,87.05,23.17,13.47,22.933003
265,3111,Daniel,Gafford,6,9,6.750000,C,234,30,WAS,Washington,East,Southeast,Washington Wizards,Wizards,14.100000,2.20,3.00,0.733,0.00,0.00,0.000,1.20,1.90,0.621,1.30,2.40,3.70,0.50,1.00,0.30,1.70,1.10,5.60,243.65,87.05,23.17,13.47,15.408018

Note: Taj Gibson's usage rate is abnormally high.

In [ ]:
bulls = appended_data[appended_data["team.abbreviation"] == "CHI"]

In [ ]:
bulls

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
27,60,Tony,Bradley,6,10,6.833333,C,248,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,0.6,0.0,0.1,0.000,0.0,0.1,0.000,0.0,0.0,0.000,0.1,0.2,0.3,0.0,0.0,0.0,0.0,0.0,0.0,247.7,89.9,26.0,14.5,7.127647
43,89,Alex,Caruso,6,5,6.416667,G,186,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,24.9,1.6,4.1,0.390,0.9,2.4,0.375,1.2,1.6,0.750,0.5,2.1,2.6,3.4,0.8,1.3,2.0,1.8,5.3,247.7,89.9,26.0,14.5,11.342406
57,125,DeMar,DeRozan,6,7,6.583333,G,220,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,33.8,8.5,17.2,0.494,0.4,1.5,0.267,8.2,9.1,0.901,0.4,3.5,3.9,4.3,0.4,1.3,2.2,2.2,25.6,247.7,89.9,26.0,14.5,29.612211
63,136,Goran,Dragic,6,3,6.250000,G,190,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,17.4,3.2,7.6,0.421,1.6,3.2,0.500,1.0,1.4,0.714,0.2,1.4,1.6,3.4,0.2,0.2,1.3,1.1,9.0,247.7,89.9,26.0,14.5,22.896953
64,137,Andre,Drummond,6,11,6.916667,C,279,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,10.0,2.3,4.3,0.535,0.0,0.2,0.000,0.8,1.2,0.667,2.2,3.9,6.1,0.5,0.3,0.6,1.7,1.1,5.4,247.7,89.9,26.0,14.5,25.351616
121,247,Derrick,Jones Jr.,6,7,6.583333,F-G,200,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,11.7,1.0,2.7,0.370,0.3,0.7,0.429,2.1,2.3,0.913,1.1,1.2,2.3,0.6,0.5,0.4,0.9,0.2,4.4,247.7,89.9,26.0,14.5,14.299157
133,268,Zach,LaVine,6,5,6.416667,G,200,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,23.4,4.8,11.4,0.421,2.2,5.2,0.423,2.7,3.2,0.844,0.2,2.6,2.8,2.8,0.1,0.8,1.3,1.3,14.5,247.7,89.9,26.0,14.5,25.783807
225,460,Nikola,Vucevic,7,0,7.000000,C,260,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,31.6,5.9,13.3,0.444,1.8,4.5,0.400,2.8,3.0,0.933,3.3,9.0,12.3,2.8,0.8,0.3,2.6,2.0,16.4,247.7,89.9,26.0,14.5,22.492690
266,3112,Ayo,Dosunmu,6,4,6.330000,G,200,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,30.1,4.5,9.3,0.485,1.3,3.9,0.333,0.9,0.9,0.923,0.5,3.3,3.8,3.1,0.3,0.9,2.4,1.7,11.1,247.7,89.9,26.0,14.5,16.191363
267,3113,Patrick,Williams,6,7,6.580000,F,215,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,25.0,3.5,7.6,0.465,1.1,2.8,0.381,0.9,0.9,0.929,1.1,2.6,3.7,0.8,1.1,0.7,1.9,1.5,9.0,247.7,89.9,26.0,14.5,16.244193
268,3114,Javonte,Green,6,5,6.420000,F,205,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,17.3,2.2,4.4,0.500,0.5,1.5,0.348,0.9,1.1,0.765,1.2,2.1,3.3,0.9,0.7,1.1,2.1,0.7,5.8,247.7,89.9,26.0,14.5,13.803740
269,3115,Coby,White,6,4,6.330000,G,195,5,CHI,Chicago,East,Central,Chicago Bulls,Bulls,21.9,3.0,7.9,0.382,1.4,4.9,0.294,0.7,1.3,0.556,0.1,1.6,1.7,1.7,0.0,0.7,2.0,0.9,8.1,247.7,89.9,26.0,14.5,18.301455

Note: Andre Drummond's usage rate is abnormally high.

In [ ]:
cavs = appended_data[appended_data["team.abbreviation"] == "CLE"]

In [ ]:
cavs

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
3,9,Jarrett,Allen,6,11,6.916667,C,237,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,33.000000,5.88,10.25,0.573,0.00,0.25,0.000,1.88,2.63,0.714,4.00,7.38,11.38,1.13,1.25,0.13,2.13,1.63,13.63,271.35,100.57,27.47,16.42,16.610474
137,277,Caris,LeVert,6,7,6.583333,G,204,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,35.616667,4.38,12.13,0.361,2.50,5.50,0.455,3.25,4.13,0.788,0.75,3.63,4.38,6.25,0.13,0.88,3.00,2.25,14.50,271.35,100.57,27.47,16.42,19.120459
141,284,Robin,Lopez,7,0,7.000000,C,275,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,6.250000,1.38,1.75,0.786,0.00,0.00,0.000,0.00,0.13,0.000,0.75,0.50,1.25,0.13,0.38,0.00,0.50,0.50,2.75,271.35,100.57,27.47,16.42,15.520898
142,285,Kevin,Love,6,10,6.833333,F-C,251,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,19.750000,4.00,8.63,0.464,2.63,6.00,0.438,1.75,2.13,0.824,0.88,6.50,7.38,2.63,0.13,0.00,1.13,0.88,12.38,271.35,100.57,27.47,16.42,22.240495
158,322,Donovan,Mitchell,6,3,6.250000,G,215,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,34.616667,9.63,20.13,0.478,3.50,8.00,0.438,4.50,5.25,0.857,0.88,3.00,3.88,6.25,0.63,1.38,2.88,3.13,27.25,271.35,100.57,27.47,16.42,31.056829
168,343,Raul,Neto,6,1,6.083333,G,179,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,10.616667,1.25,3.00,0.417,0.38,1.13,0.333,0.75,0.75,1.000,0.25,1.25,1.50,1.63,0.00,0.50,0.75,0.50,3.63,271.35,100.57,27.47,16.42,15.167787
177,359,Cedi,Osman,6,8,6.666667,F,215,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,24.000000,3.63,8.38,0.433,1.88,4.88,0.385,1.38,1.75,0.786,0.38,2.38,2.75,2.25,0.13,0.13,2.63,1.13,10.50,271.35,100.57,27.47,16.42,18.009162
270,3116,Darius,Garland,6,1,6.080000,G,192,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,34.600000,7.00,17.80,0.394,3.40,7.90,0.429,4.00,5.10,0.780,0.50,2.00,2.50,8.00,0.30,1.40,2.40,2.90,21.40,271.35,100.57,27.47,16.42,27.880764
271,3117,Evan,Mobley,6,11,6.920000,F,215,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,33.700000,6.20,11.10,0.561,0.10,0.80,0.182,2.60,3.70,0.692,2.40,5.10,7.50,2.10,1.40,0.90,3.10,2.20,15.10,271.35,100.57,27.47,16.42,18.624446
272,3118,Dean,Wade,6,9,6.750000,F,228,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,22.800000,2.50,4.60,0.529,1.60,3.30,0.500,0.70,1.00,0.727,0.50,2.80,3.30,1.00,0.40,0.50,2.50,0.40,7.30,271.35,100.57,27.47,16.42,10.031727
273,3119,Isaac,Okoro,6,5,6.420000,F,225,6,CLE,Cleveland,East,Central,Cleveland Cavaliers,Cavaliers,16.400000,1.00,2.80,0.359,0.10,1.00,0.071,0.60,0.90,0.750,0.40,1.00,1.40,0.40,0.10,0.60,2.10,0.90,2.70,271.35,100.57,27.47,16.42,10.500929

Note: Nothing peculiar with the Cavs with regards to usage rate.

In [ ]:
pistons = appended_data[appended_data["team.abbreviation"] == "DET"]

In [ ]:
pistons

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
24,54,Bojan,Bogdanovic,6,8,6.666667,F,216,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,31.2,6.6,13.2,0.500,3.4,7.0,0.486,3.6,3.8,0.947,0.6,2.7,3.3,1.9,0.0,0.5,2.2,1.8,20.2,255.1,92.7,27.8,15.1,22.713106
58,128,Hamidou,Diallo,6,5,6.416667,G,198,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,13.1,1.7,4.6,0.370,0.0,0.4,0.000,1.2,2.0,0.600,0.9,1.9,2.8,0.8,0.1,0.5,2.1,0.5,4.6,255.1,92.7,27.8,15.1,19.403197
125,251,Cory,Joseph,6,3,6.250000,G,193,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,12.6,1.0,2.6,0.385,0.6,1.4,0.429,0.5,0.6,0.833,0.2,0.9,1.1,2.4,0.1,0.2,1.3,0.5,3.1,255.1,92.7,27.8,15.1,11.348249
129,259,Kevin,Knox,6,9,6.750000,F,215,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,5.8,0.6,2.3,0.261,0.2,1.5,0.133,0.0,0.0,0.000,0.2,0.6,0.8,0.1,0.1,0.1,0.9,0.3,1.4,255.1,92.7,27.8,15.1,19.054114
152,307,Rodney,McGruder,6,4,6.333333,F-G,200,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,1.6,0.1,0.6,0.167,0.1,0.4,0.250,0.0,0.0,0.000,0.1,0.2,0.3,0.1,0.0,0.0,0.1,0.0,0.3,255.1,92.7,27.8,15.1,15.939499
170,345,Nerlens,Noel,6,11,6.916667,F-C,220,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,5.1,0.3,1.0,0.300,0.0,0.0,0.000,0.2,0.2,1.000,0.2,1.1,1.3,0.3,0.1,0.2,0.5,0.3,0.8,255.1,92.7,27.8,15.1,11.568118
274,3120,Cade,Cunningham,6,6,6.500000,G,220,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,33.3,7.8,18.7,0.415,1.4,5.1,0.279,3.0,3.6,0.837,1.0,5.2,6.2,6.0,0.6,0.8,2.8,3.3,19.9,255.1,92.7,27.8,15.1,30.103476
275,3121,Jaden,Ivey,6,4,6.330000,G,200,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,32.0,5.9,13.5,0.433,1.5,4.6,0.319,3.1,4.2,0.730,1.3,3.7,4.9,4.1,0.3,1.3,3.1,2.7,16.3,255.1,92.7,27.8,15.1,23.973007
276,3122,Isaiah,Stewart,6,9,6.750000,C,250,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,27.0,3.8,8.0,0.475,1.2,3.6,0.333,3.2,4.3,0.738,2.9,6.5,9.3,1.3,0.7,0.5,3.0,1.1,12.0,255.1,92.7,27.8,15.1,17.304393
277,3123,Killian,Hayes,6,5,6.420000,G,216,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,21.2,2.1,7.0,0.295,0.5,2.2,0.229,0.7,0.9,0.786,0.5,2.1,2.6,3.3,0.4,1.1,2.4,1.6,5.3,255.1,92.7,27.8,15.1,18.036697
278,3124,Saddiq,Bey,6,8,6.670000,F,215,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,31.6,4.8,11.5,0.413,1.7,5.7,0.297,4.2,4.6,0.918,1.2,3.7,4.9,1.6,0.2,0.9,1.8,1.4,15.4,255.1,92.7,27.8,15.1,20.074354
279,3125,Isaiah,Livers,6,7,6.580000,F,230,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,19.1,1.8,4.9,0.362,1.4,3.9,0.345,0.9,1.2,0.765,0.7,1.9,2.6,0.6,0.4,0.4,1.9,0.5,5.9,255.1,92.7,27.8,15.1,13.192231
280,3126,Jalen,Duren,6,10,6.830000,C,250,9,DET,Detroit,East,Central,Detroit Pistons,Pistons,21.5,2.7,4.8,0.556,0.0,0.1,0.000,0.9,2.4,0.387,2.9,4.5,7.4,0.3,1.2,0.3,2.1,1.1,6.3,255.1,92.7,27.8,15.1,13.751958

Note: Nothing peculiar with the pistons with regard to usage rate.

In [ ]:
pacers = appended_data[appended_data["team.abbreviation"] == "IND"]

In [ ]:
pacers

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
101,210,Buddy,Hield,6,4,6.333333,G,214,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,31.100000,6.78,14.22,0.477,4.11,9.67,0.425,0.89,1.00,0.889,1.22,4.56,5.78,3.67,0.22,0.78,2.00,2.11,18.56,230.033333,87.33,22.74,15.75,21.937450
119,242,James,Johnson,6,8,6.666667,F,240,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,4.883333,0.56,1.33,0.417,0.11,0.56,0.200,0.00,0.00,0.000,0.00,0.78,0.78,0.44,0.22,0.11,1.11,0.00,1.22,230.033333,87.33,22.74,15.75,11.080229
149,304,T.J.,McConnell,6,2,6.166667,G,190,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,13.766667,1.56,4.56,0.341,0.00,0.22,0.000,0.00,0.00,0.000,0.44,1.44,1.89,2.56,0.22,1.22,0.78,1.22,3.11,230.033333,87.33,22.74,15.75,17.080969
220,452,Myles,Turner,6,11,6.916667,C-F,250,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,11.883333,1.89,4.22,0.447,0.44,1.44,0.308,1.89,2.44,0.773,0.56,2.56,3.11,0.78,1.56,0.11,1.44,1.22,6.11,230.033333,87.33,22.74,15.75,22.299559
281,3127,Tyrese,Haliburton,6,5,6.420000,G,185,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,34.000000,7.40,15.00,0.492,3.00,7.10,0.424,2.80,3.30,0.860,1.00,3.50,4.50,10.40,0.20,1.90,1.30,3.00,20.60,230.033333,87.33,22.74,15.75,23.275489
282,3128,Bennedict,Mathurin,6,6,6.500000,G,210,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,27.600000,6.20,13.30,0.462,2.70,5.90,0.455,4.90,5.90,0.831,1.30,2.50,3.80,2.10,0.10,0.40,2.20,2.30,19.90,230.033333,87.33,22.74,15.75,26.821330
283,3129,Chris,Duarte,6,5,6.420000,G,190,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,19.700000,3.10,7.90,0.394,1.40,4.20,0.342,1.20,1.30,0.917,0.40,1.70,2.10,1.00,0.40,0.10,1.80,0.90,8.90,230.033333,87.33,22.74,15.75,19.354391
284,3130,Jalen,Smith,6,9,6.750000,F,215,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,24.000000,4.20,9.50,0.435,1.20,4.10,0.302,1.50,2.20,0.679,1.80,5.80,7.50,1.10,0.80,0.20,2.20,1.50,11.00,230.033333,87.33,22.74,15.75,20.287279
285,3131,Oshae,Brissett,6,7,6.580000,F,210,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,10.900000,0.90,2.40,0.368,0.40,1.50,0.250,0.60,0.80,0.833,0.60,1.00,1.60,0.40,0.00,0.30,0.50,0.50,2.80,230.033333,87.33,22.74,15.75,12.137731
286,3132,Isaiah,Jackson,6,9,6.750000,F,205,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,18.300000,3.20,5.20,0.618,0.00,0.10,0.000,1.90,2.80,0.676,1.50,3.50,5.10,1.20,1.40,0.50,2.60,1.20,8.40,230.033333,87.33,22.74,15.75,16.966831
287,3133,Aaron,Nesmith,6,5,6.420000,F,215,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,20.800000,2.40,6.30,0.386,1.00,3.40,0.290,1.00,1.20,0.818,0.30,2.80,3.10,1.60,0.80,0.30,2.60,1.00,6.90,230.033333,87.33,22.74,15.75,15.310908
288,3134,Goga,Bitadze,6,11,6.920000,C,250,12,IND,Indiana,East,Central,Indiana Pacers,Pacers,13.100000,1.80,3.40,0.519,0.10,0.90,0.143,0.90,1.80,0.500,1.60,1.80,3.40,1.50,0.50,0.50,2.30,0.80,4.50,230.033333,87.33,22.74,15.75,15.503036

Note: Nothing peculiar with the pacers with regard to usage rate.

In [ ]:
bucks = appended_data[appended_data["team.abbreviation"] == "MIL"]

In [ ]:
bucks

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
2,8,Grayson,Allen,6,5,6.416667,G,198,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,26.000000,3.00,7.44,0.403,2.00,4.89,0.409,2.00,2.22,0.900,0.78,2.33,3.11,2.33,0.11,1.00,1.22,1.44,10.00,233.633333,88.68,24.26,12.79,15.796098
5,15,Giannis,Antetokounmpo,6,11,6.916667,F,242,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,29.666667,10.44,18.89,0.553,0.89,3.22,0.276,7.22,11.44,0.631,1.78,9.56,11.33,5.11,1.33,0.89,2.56,2.78,29.00,233.633333,88.68,24.26,12.79,37.504922
42,87,Jevon,Carter,6,2,6.166667,G,196,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,23.883333,2.00,5.56,0.360,1.33,3.89,0.343,0.33,0.33,1.000,0.67,1.56,2.22,1.56,0.56,1.67,2.89,1.11,5.67,233.633333,88.68,24.26,12.79,11.889699
102,211,George,Hill,6,3,6.250000,G,188,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,21.216667,1.67,3.78,0.441,0.56,2.00,0.278,1.33,2.00,0.667,0.33,1.56,1.89,2.44,0.00,0.22,1.78,0.67,5.22,233.633333,88.68,24.26,12.79,10.467363
104,214,Jrue,Holiday,6,4,6.333333,G,205,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,33.766667,7.44,17.11,0.435,2.44,6.78,0.361,2.67,3.11,0.857,1.33,4.33,5.67,8.00,0.67,1.44,1.67,2.33,20.00,233.633333,88.68,24.26,12.79,25.676611
109,223,Serge,Ibaka,6,10,6.833333,F-C,235,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,8.433333,0.89,2.00,0.444,0.33,0.78,0.429,0.56,0.67,0.833,0.44,1.56,2.00,0.22,0.56,0.00,1.22,0.67,2.67,233.633333,88.68,24.26,12.79,14.648169
140,283,Brook,Lopez,7,0,7.000000,C,270,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,30.333333,5.78,11.56,0.500,2.33,6.33,0.368,1.11,1.33,0.833,2.22,4.33,6.56,1.00,2.56,0.67,2.78,1.44,15.00,233.633333,88.68,24.26,12.79,18.660922
147,301,Wesley,Matthews,6,4,6.330000,G-F,220,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,14.883333,1.11,3.44,0.323,0.89,2.78,0.320,0.33,0.44,0.750,1.33,1.22,2.56,0.67,0.22,0.67,1.67,0.56,3.44,233.633333,88.68,24.26,12.79,11.740160
186,377,Bobby,Portis,6,11,6.916667,F,250,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,25.666667,5.56,12.00,0.463,1.33,4.00,0.333,0.89,1.22,0.727,2.89,8.33,11.22,2.00,0.33,0.33,1.33,0.89,13.33,233.633333,88.68,24.26,12.79,21.796676
242,2148,Thanasis,Antetokounmpo,6,6,6.500000,F,219,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,0.883333,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.22,0.22,0.00,0.11,0.00,0.11,0.00,0.00,233.633333,88.68,24.26,12.79,0.000000
289,3135,Jordan,Nwora,6,8,6.670000,F,225,17,MIL,Milwaukee,East,Central,Milwaukee Bucks,Bucks,18.900000,2.30,6.90,0.333,1.30,3.70,0.346,1.40,1.50,0.905,0.80,3.30,4.10,1.00,0.10,0.40,1.10,0.90,7.20,233.633333,88.68,24.26,12.79,18.650727

Note: Nothing peculiar with the bucks with regards to usage rate.

In [ ]:
celtics = appended_data[appended_data["team.abbreviation"] == "BOS"]

In [ ]:
celtics

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
29,65,Malcolm,Brogdon,6,5,6.416667,G,229,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,24.216667,5.22,10.56,0.495,1.22,3.22,0.379,3.22,3.56,0.906,0.67,2.67,3.33,3.78,0.11,0.67,1.56,1.89,14.89,252.416667,87.59,23.77,13.02,26.307408
33,70,Jaylen,Brown,6,7,6.583333,G,220,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,37.100000,9.11,20.00,0.456,2.67,7.56,0.353,4.44,5.22,0.851,1.11,5.33,6.44,2.89,0.67,0.89,3.00,2.78,25.33,252.416667,87.59,23.77,13.02,30.722330
88,189,Blake,Griffin,6,10,6.833333,F,250,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,5.433333,0.56,1.33,0.417,0.22,0.56,0.400,0.56,0.67,0.833,0.56,0.78,1.33,0.56,0.00,0.22,1.00,0.44,1.89,252.416667,87.59,23.77,13.02,17.272993
107,219,Al,Horford,6,10,6.833333,C-F,245,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,24.333333,2.67,5.78,0.462,1.33,3.78,0.353,0.33,0.44,0.750,0.89,3.78,4.67,1.67,0.56,0.11,1.89,0.78,7.00,252.416667,87.59,23.77,13.02,12.615070
116,235,Justin,Jackson,6,8,6.666667,F,210,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,1.100000,0.22,0.44,0.500,0.22,0.33,0.667,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00,0.67,252.416667,87.59,23.77,13.02,18.180923
131,261,Luke,Kornet,7,1,7.083333,F-C,250,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,8.100000,0.56,1.11,0.500,0.11,0.33,0.333,0.33,0.44,0.750,0.67,1.11,1.78,0.89,0.56,0.22,0.78,0.44,1.56,252.416667,87.59,23.77,13.02,9.784030
210,420,Marcus,Smart,6,4,6.333333,G,220,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,33.666667,3.67,9.56,0.384,1.56,5.56,0.280,2.00,2.22,0.900,0.22,2.89,3.11,6.00,0.22,1.00,3.00,1.67,10.89,252.416667,87.59,23.77,13.02,16.480017
214,434,Jayson,Tatum,6,8,6.666667,F,208,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,37.550000,9.78,19.56,0.500,3.44,9.00,0.383,7.33,8.11,0.904,0.89,7.11,8.00,4.22,1.44,0.89,1.89,2.78,30.33,252.416667,87.59,23.77,13.02,31.360761
224,459,Noah,Vonleh,6,9,6.750000,F,250,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,9.883333,1.11,1.89,0.588,0.11,0.11,1.000,0.00,0.00,0.000,1.33,1.56,2.89,0.11,0.67,0.22,2.11,0.67,2.33,252.416667,87.59,23.77,13.02,11.773144
232,473,Derrick,White,6,4,6.333333,G,190,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,26.433333,3.00,6.56,0.458,1.44,3.44,0.419,0.89,1.11,0.800,0.56,2.78,3.33,2.78,0.78,0.56,3.11,0.67,8.33,252.416667,87.59,23.77,13.02,13.271845
290,3136,Grant,Williams,6,6,6.500000,F,236,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,28.200000,3.40,5.70,0.588,1.80,3.60,0.500,1.40,1.70,0.833,0.70,4.00,4.70,1.70,0.60,0.60,2.70,0.80,9.90,252.416667,87.59,23.77,13.02,11.682210
291,3137,Sam,Hauser,6,7,6.580000,F,217,2,BOS,Boston,East,Atlantic,Boston Celtics,Celtics,16.400000,2.70,5.10,0.532,2.20,4.50,0.485,0.20,0.30,0.750,0.30,1.90,2.20,0.50,0.30,0.30,1.30,0.10,7.90,252.416667,87.59,23.77,13.02,14.777543

Note: Nothing peculiar with the Celtics with regard to usage rate.

In [ ]:
nets = appended_data[appended_data["team.abbreviation"] == "BKN"]

In [ ]:
nets

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
52,114,Seth,Curry,6,2,6.166667,G,185,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,3.2,0.1,0.9,0.111,0.1,0.7,0.143,0.0,0.0,0.000,0.0,0.2,0.2,0.6,0.1,0.1,0.3,0.1,0.3,237.6,84.1,24.8,12.7,13.786765
65,140,Kevin,Durant,6,9,6.750000,F,240,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,37.2,10.5,20.3,0.517,1.7,5.1,0.333,8.8,9.3,0.946,0.4,5.8,6.2,4.8,2.0,0.8,2.3,3.5,31.5,237.6,84.1,24.8,12.7,33.078748
93,197,Joe,Harris,6,6,6.500000,F-G,218,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,19.1,2.0,5.3,0.377,1.2,3.8,0.316,0.1,0.3,0.333,0.8,1.9,2.7,1.6,0.3,0.4,1.9,0.3,5.3,237.6,84.1,24.8,12.7,13.239914
113,228,Kyrie,Irving,6,3,6.250000,G,193,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,31.0,7.8,17.2,0.453,2.1,7.5,0.280,3.8,4.1,0.927,0.6,3.5,4.1,4.1,0.9,1.2,2.4,1.9,21.5,237.6,84.1,24.8,12.7,29.749526
156,319,Patty,Mills,6,0,6.000000,G,180,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,13.9,2.1,4.4,0.477,1.6,3.5,0.457,1.0,1.0,1.000,0.2,0.5,0.7,0.9,0.1,0.2,0.7,0.3,6.8,237.6,84.1,24.8,12.7,16.314008
161,329,Markieff,Morris,6,9,6.750000,F,245,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,5.2,0.5,1.6,0.313,0.5,1.2,0.417,0.0,0.0,0.000,0.1,1.1,1.2,0.4,0.1,0.2,0.8,0.4,1.5,237.6,84.1,24.8,12.7,16.968326
173,351,Royce,O'Neale,6,6,6.500000,F,226,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,36.3,3.8,9.6,0.396,2.4,5.9,0.407,0.5,0.6,0.833,0.9,3.3,4.2,3.8,0.7,1.2,3.5,0.9,10.5,237.6,84.1,24.8,12.7,13.082158
208,417,Ben,Simmons,6,10,6.833333,G-F,230,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,19.1,1.5,3.4,0.441,0.0,0.1,0.000,0.7,1.5,0.467,0.6,3.3,3.9,4.3,0.4,0.7,2.6,1.6,3.7,237.6,84.1,24.8,12.7,13.073606
213,432,Edmond,Sumner,6,6,6.500000,G,176,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,12.0,1.4,3.8,0.368,0.3,1.3,0.231,1.7,1.7,1.000,0.2,1.1,1.3,1.2,0.2,0.5,0.7,1.0,4.8,237.6,84.1,24.8,12.7,20.397059
230,470,Yuta,Watanabe,6,9,6.750000,G,205,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,15.4,2.1,3.4,0.618,1.1,1.9,0.579,0.0,0.2,0.000,0.5,1.9,2.4,0.5,0.6,0.3,1.0,0.3,5.3,237.6,84.1,24.8,12.7,10.851795
292,3138,Nic,Claxton,6,11,6.920000,C,215,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,26.8,5.3,7.4,0.712,0.0,0.1,0.000,1.0,2.6,0.381,2.6,5.7,8.3,1.3,1.8,0.8,2.8,1.4,11.5,237.6,84.1,24.8,12.7,16.369622
293,3139,Cam,Thomas,6,3,6.250000,G,210,3,BKN,Brooklyn,East,Atlantic,Brooklyn Nets,Nets,18.4,2.6,6.8,0.387,0.5,1.5,0.353,2.9,3.5,0.842,0.1,1.5,1.6,2.1,0.2,0.7,0.9,1.0,8.7,237.6,84.1,24.8,12.7,22.394501

Note: Nothing peculiar with the Nets with regard to usage rate.

In [ ]:
knicks = appended_data[appended_data["team.abbreviation"] == "NYK"]

In [ ]:
knicks

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
8,19,Ryan,Arcidiacono,6,3,6.250000,G,200,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,0.216667,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00,0.00,253.466667,95.53,23.71,13.84,0.000000
34,73,Jalen,Brunson,6,3,6.250000,G,190,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,33.883333,7.44,15.11,0.493,1.11,3.78,0.294,3.33,4.22,0.789,0.33,3.56,3.89,7.22,0.22,0.89,2.56,1.56,19.33,253.466667,95.53,23.71,13.84,23.136604
70,160,Evan,Fournier,6,7,6.583333,G-F,205,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,21.766667,3.11,7.78,0.400,1.89,4.89,0.386,0.67,0.78,0.857,0.11,2.33,2.44,1.56,0.22,0.67,2.56,1.11,8.78,253.466667,95.53,23.71,13.84,17.949223
95,201,Isaiah,Hartenstein,7,0,7.000000,F-C,249,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,25.883333,3.78,6.78,0.557,0.22,1.22,0.182,0.67,0.89,0.750,3.67,5.00,8.67,1.00,1.56,0.89,2.67,0.89,8.44,253.466667,95.53,23.71,13.84,13.179119
166,338,Svi,Mykhailiuk,6,8,6.666667,G,205,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,0.216667,0.11,0.11,1.000,0.11,0.11,1.000,0.00,0.00,0.000,0.00,0.22,0.22,0.00,0.00,0.00,0.00,0.00,0.33,253.466667,95.53,23.71,13.84,21.482554
191,387,Julius,Randle,6,9,6.750000,F,250,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,34.000000,6.56,14.78,0.444,1.11,4.56,0.244,4.67,6.33,0.737,2.56,6.56,9.11,3.33,0.33,0.89,3.67,2.89,18.89,253.466667,95.53,23.71,13.84,25.457171
196,399,Mitchell,Robinson,7,1,7.083333,C,240,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,19.333333,2.56,3.67,0.697,0.00,0.00,0.000,0.67,1.56,0.429,3.11,2.56,5.67,0.89,2.00,0.33,3.22,0.56,5.78,253.466667,95.53,23.71,13.84,10.760335
197,401,Derrick,Rose,6,3,6.250000,G,200,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,12.766667,2.78,6.00,0.463,1.22,2.56,0.478,0.33,0.33,1.000,0.33,1.67,2.00,2.11,0.22,0.22,0.67,1.33,7.11,253.466667,95.53,23.71,13.84,24.775968
294,3140,Cam,Reddish,6,8,6.670000,F,217,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,23.200000,3.40,7.40,0.459,1.00,3.00,0.333,1.30,1.50,0.870,0.30,1.50,1.90,1.00,0.50,0.80,1.70,0.70,9.10,253.466667,95.53,23.71,13.84,15.977229
295,3141,RJ,Barrett,6,6,6.500000,G,214,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,34.000000,6.50,16.30,0.402,1.50,5.70,0.256,3.80,5.10,0.740,0.90,4.20,5.10,2.90,0.10,0.50,2.20,2.10,18.30,253.466667,95.53,23.71,13.84,25.692139
296,3142,Immanuel,Quickley,6,3,6.250000,G,190,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,22.100000,3.10,8.10,0.380,1.10,3.90,0.293,1.60,2.00,0.800,0.50,4.30,4.80,3.30,0.10,1.30,1.90,1.30,8.90,253.466667,95.53,23.71,13.84,19.682768
297,3143,Quentin,Grimes,6,4,6.330000,G,210,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,8.000000,0.60,1.80,0.333,0.40,1.60,0.250,0.40,0.40,1.000,0.20,0.40,0.60,0.40,0.20,0.00,1.20,0.40,2.00,253.466667,95.53,23.71,13.84,12.567294
298,3144,Obi,Toppin,6,9,6.750000,F,220,20,NYK,New York,East,Atlantic,New York Knicks,Knicks,18.100000,3.70,7.70,0.483,1.70,4.30,0.406,0.60,0.60,1.000,0.80,3.20,4.00,1.20,0.20,0.50,0.90,1.00,9.80,253.466667,95.53,23.71,13.84,20.956010

Note: Svi has an abnormally high usage rate.

In [ ]:
sixers = appended_data[appended_data["team.abbreviation"] == "PHI"]

In [ ]:
sixers

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
66,145,Joel,Embiid,7,0,7.000000,F-C,250,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,20.7,5.8,10.9,0.532,0.6,2.0,0.300,4.1,5.2,0.788,0.8,4.9,5.7,2.0,0.7,0.3,1.9,2.2,16.3,245.7,83.9,20.9,12.3,34.659545
90,192,James,Harden,6,5,6.416667,G,220,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,33.1,6.3,14.3,0.441,2.0,6.0,0.333,5.2,5.6,0.929,0.5,5.8,6.3,9.0,0.6,1.0,1.8,2.6,19.8,245.7,83.9,20.9,12.3,27.275838
91,194,Montrezl,Harrell,6,8,6.666667,F-C,240,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,12.2,1.3,2.5,0.520,0.0,0.0,0.000,1.4,2.0,0.700,0.5,1.5,2.0,0.5,0.5,0.3,1.2,0.3,4.0,245.7,83.9,20.9,12.3,14.063681
94,200,Tobias,Harris,6,9,6.750000,F,235,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,33.0,5.5,11.1,0.495,2.5,5.6,0.446,0.9,1.4,0.643,1.3,5.2,6.5,2.7,0.8,1.4,2.2,0.8,14.4,245.7,83.9,20.9,12.3,17.683272
130,260,Furkan,Korkmaz,6,7,6.583333,G-F,190,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,1.6,0.1,0.4,0.250,0.1,0.3,0.333,0.0,0.0,0.000,0.1,0.2,0.3,0.2,0.0,0.0,0.0,0.2,0.3,245.7,83.9,20.9,12.3,17.484060
153,313,De'Anthony,Melton,6,4,6.333333,G,200,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,21.1,3.5,7.8,0.449,1.4,3.8,0.368,0.4,0.5,0.800,0.6,2.2,2.8,2.7,0.3,1.8,1.3,0.6,8.8,245.7,83.9,20.9,12.3,19.047406
157,320,Shake,Milton,6,6,6.500000,G,207,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,6.3,0.9,2.2,0.409,0.1,0.5,0.200,0.0,0.0,0.000,0.3,0.7,1.0,0.8,0.1,0.0,1.0,0.7,1.9,245.7,83.9,20.9,12.3,21.461915
169,344,Georges,Niang,6,8,6.666667,F,230,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,16.8,2.8,5.9,0.475,2.0,4.4,0.455,0.2,0.2,1.000,0.2,1.7,1.9,0.5,0.2,0.1,1.9,0.6,7.8,245.7,83.9,20.9,12.3,18.283331
219,450,PJ,Tucker,6,6,6.500000,F,245,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,28.3,2.3,4.2,0.548,1.0,2.2,0.455,0.3,0.4,0.750,1.5,2.8,4.3,0.7,0.5,0.5,2.9,1.1,5.9,245.7,83.9,20.9,12.3,9.021693
243,2175,Danuel,House Jr.,6,7,6.583333,F,220,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,14.8,1.0,2.7,0.370,0.5,1.6,0.313,0.8,1.1,0.727,0.4,1.4,1.8,0.9,0.1,0.3,1.2,0.6,3.3,245.7,83.9,20.9,12.3,11.920664
299,3145,Tyrese,Maxey,6,2,6.170000,G,200,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,37.5,8.4,18.6,0.448,2.9,7.0,0.408,3.2,4.3,0.750,0.4,3.0,3.4,4.4,0.2,1.1,2.5,2.1,22.8,245.7,83.9,20.9,12.3,28.088881
300,3146,Paul,Reed,6,9,6.750000,F,210,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,7.2,0.3,1.2,0.231,0.0,0.2,0.000,0.0,0.0,0.000,0.5,1.2,1.6,0.1,0.5,1.0,1.8,0.3,0.5,245.7,83.9,20.9,12.3,9.713367
301,3147,Matisse,Thybulle,6,5,6.420000,G,201,23,PHI,Philadelphia,East,Atlantic,Philadelphia 76ers,76ers,13.1,0.6,2.1,0.296,0.2,1.2,0.188,0.1,0.2,0.333,0.3,1.2,1.5,0.6,0.4,1.0,1.3,0.2,1.5,245.7,83.9,20.9,12.3,8.499122

Note: Shake Milton has an abnormally high usage rate.

In [ ]:
raptors = appended_data[appended_data["team.abbreviation"] == "TOR"]

In [ ]:
raptors

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
7,18,OG,Anunoby,6,8,6.666667,F,232,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,34.433333,5.67,12.00,0.472,2.00,4.89,0.409,2.22,2.67,0.833,1.11,5.22,6.33,1.78,0.89,3.11,3.67,2.11,15.56,234.85,92.51,24.57,12.24,18.042251
21,46,Khem,Birch,6,9,6.750000,C,233,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,3.666667,0.33,0.56,0.600,0.11,0.11,1.000,0.22,0.22,1.000,0.33,0.22,0.56,0.11,0.11,0.33,0.89,0.11,1.00,234.85,92.51,24.57,12.24,8.500035
26,58,Chris,Boucher,6,10,6.833333,F,200,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,14.100000,3.22,5.44,0.592,1.22,2.44,0.500,0.78,1.22,0.636,1.11,2.11,3.22,0.56,0.67,0.56,2.22,0.44,8.44,234.85,92.51,24.57,12.24,18.497346
99,206,Juancho,Hernangomez,6,9,6.750000,F,230,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,2.550000,0.00,0.22,0.000,0.00,0.22,0.000,0.00,0.00,0.000,0.00,0.22,0.22,0.22,0.11,0.11,0.22,0.11,0.00,234.85,92.51,24.57,12.24,5.259976
185,376,Otto,Porter Jr.,6,8,6.666667,F,198,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,3.433333,0.33,0.56,0.600,0.33,0.56,0.600,0.22,0.22,1.000,0.00,0.33,0.33,0.00,0.00,0.44,0.11,0.00,1.22,234.85,92.51,24.57,12.24,7.775480
207,416,Pascal,Siakam,6,9,6.750000,F,230,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,35.666667,8.89,18.56,0.479,1.44,4.22,0.342,5.56,7.67,0.725,1.78,7.56,9.33,7.67,0.56,0.89,3.11,2.67,24.78,234.85,92.51,24.57,12.24,28.039311
223,458,Fred,VanVleet,6,0,6.000000,G,195,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,25.333333,2.67,7.56,0.353,1.56,4.11,0.378,2.00,2.33,0.857,0.67,2.00,2.67,5.11,0.44,1.67,1.78,0.78,8.89,234.85,92.51,24.57,12.24,15.025701
239,489,Thaddeus,Young,6,8,6.666667,F,221,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,5.000000,0.67,1.44,0.462,0.11,0.56,0.200,0.11,0.22,0.500,0.22,0.56,0.78,0.33,0.00,0.56,0.67,0.22,1.56,234.85,92.51,24.57,12.24,14.281122
245,3089,Gary,Trent Jr.,6,6,6.500000,G,205,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,35.766667,6.78,15.67,0.433,3.00,8.33,0.360,2.56,3.22,0.793,0.89,1.00,1.89,1.22,0.22,1.33,1.11,1.00,19.11,234.85,92.51,24.57,12.24,20.553855
302,3148,Scottie,Barnes,6,7,6.580000,F,225,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,32.700000,5.70,12.70,0.447,1.20,3.60,0.333,1.20,1.70,0.720,1.90,4.60,6.50,4.90,0.70,0.90,1.50,2.20,13.70,234.85,92.51,24.57,12.24,19.450067
303,3149,Malachi,Flynn,6,1,6.080000,G,175,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,10.600000,2.00,4.60,0.439,1.20,2.60,0.478,1.10,1.20,0.909,0.10,1.10,1.20,1.00,0.10,0.30,1.40,0.60,6.30,234.85,92.51,24.57,12.24,21.963784
304,3150,Dalano,Banton,6,7,6.580000,G,204,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,11.200000,2.30,5.50,0.427,0.80,2.50,0.324,0.90,1.10,0.875,0.50,0.90,1.40,1.10,0.70,0.60,1.10,0.70,6.40,234.85,92.51,24.57,12.24,24.256517
305,3151,Precious,Achiuwa,6,8,6.670000,F,225,28,TOR,Toronto,East,Atlantic,Toronto Raptors,Raptors,20.400000,3.00,7.70,0.391,0.40,2.30,0.179,2.30,2.80,0.848,2.00,5.00,7.00,1.30,0.60,0.20,1.60,1.30,8.80,234.85,92.51,24.57,12.24,20.386393

Note: Fred Vanvleet will have a lower usage rate than other players because of the lack of time spent on the court, which makes sense.

In [ ]:
nuggets = appended_data[appended_data["team.abbreviation"] == "DEN"]

In [ ]:
nuggets

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
32,69,Bruce,Brown,6,5,6.416667,G,202,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,27.100000,4.33,8.89,0.487,1.56,3.67,0.424,0.67,1.00,0.667,1.11,2.11,3.22,4.00,0.33,0.67,1.89,1.11,10.89,224.6,84.79,20.8,14.79,15.915254
39,81,Kentavious,Caldwell-Pope,6,5,6.416667,G,205,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,27.766667,3.56,7.33,0.485,2.33,4.33,0.538,0.67,1.00,0.667,0.33,2.78,3.11,2.67,0.44,1.22,2.11,1.00,10.11,224.6,84.79,20.8,14.79,13.048429
80,177,Aaron,Gordon,6,9,6.750000,F,220,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,28.433333,6.00,10.67,0.563,0.89,3.11,0.286,1.67,3.00,0.556,2.22,4.00,6.22,2.00,1.11,0.22,1.22,1.11,14.56,224.6,84.79,20.8,14.79,19.033817
87,188,Jeff,Green,6,9,6.750000,F,235,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,20.333333,3.11,6.22,0.500,0.56,1.56,0.357,1.89,2.56,0.739,1.00,2.33,3.33,1.22,0.00,0.67,2.00,1.00,8.67,224.6,84.79,20.8,14.79,16.957936
120,246,Nikola,Jokic,7,0,7.000000,C,250,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,32.550000,7.33,11.78,0.623,0.56,2.22,0.250,5.11,5.78,0.885,1.67,9.11,10.78,9.22,0.44,1.33,2.67,3.56,20.33,224.6,84.79,20.8,14.79,22.697426
124,250,DeAndre,Jordan,6,11,6.916667,C,265,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,10.100000,2.00,2.44,0.818,0.11,0.11,1.000,0.56,1.33,0.417,1.22,3.33,4.56,0.44,0.44,0.11,1.56,0.89,4.67,224.6,84.79,20.8,14.79,16.014558
164,335,Jamal,Murray,6,4,6.333333,G,207,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,24.100000,5.33,12.33,0.432,1.67,4.33,0.385,1.00,1.44,0.692,0.22,2.22,2.44,3.33,0.00,0.78,0.44,1.78,13.33,224.6,84.79,20.8,14.79,25.273702
184,375,Michael,Porter Jr.,6,10,6.833333,F,210,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,25.883333,5.33,11.22,0.475,3.22,6.56,0.492,1.33,1.67,0.800,1.56,5.11,6.67,1.00,0.22,0.56,3.11,1.22,15.22,224.6,84.79,20.8,14.79,21.028398
192,390,Davon,Reed,6,5,6.416667,G,208,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,4.883333,0.33,1.22,0.273,0.22,0.56,0.400,0.11,0.22,0.500,0.00,0.44,0.44,0.11,0.00,0.33,0.56,0.78,1.00,224.6,84.79,20.8,14.79,17.738750
212,422,Ish,Smith,6,0,6.000000,G,175,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,2.550000,0.22,0.89,0.250,0.00,0.11,0.000,0.00,0.00,0.000,0.00,0.22,0.22,0.22,0.11,0.00,0.44,0.44,0.44,224.6,84.79,20.8,14.79,21.547348
306,3152,Bones,Hyland,6,2,6.170000,G,169,8,DEN,Denver,West,Northwest,Denver Nuggets,Nuggets,20.900000,4.70,11.80,0.398,3.10,6.20,0.500,2.20,2.80,0.786,0.10,2.10,2.20,3.50,0.30,0.60,2.00,1.90,14.70,224.6,84.79,20.8,14.79,29.515767

Note: Ish Smith and Bones Hyland have high usage rates. The numbers might be skewed due to the lack of time that Michael Porter Jr and Jamal Murray shared together.

In [ ]:
timberwolves = appended_data[appended_data["team.abbreviation"] == "MIN"]

In [ ]:
timberwolves

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
4,12,Kyle,Anderson,6,9,6.750000,F,230,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,10.2,0.8,1.3,0.615,0.2,0.4,0.500,0.9,1.1,0.818,0.4,1.3,1.7,1.4,0.2,0.4,0.8,0.4,2.7,243.4,90.0,23.1,15.6,9.003876
69,159,Bryn,Forbes,6,3,6.250000,G,190,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,6.0,0.4,1.8,0.222,0.1,0.8,0.125,0.4,0.4,1.000,0.3,0.2,0.5,0.4,0.0,0.3,0.4,0.2,1.3,243.4,90.0,23.1,15.6,15.250521
79,176,Rudy,Gobert,7,1,7.083333,C,245,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,29.1,4.3,7.3,0.589,0.0,0.2,0.000,2.7,4.3,0.628,4.2,8.3,12.5,1.0,1.4,0.6,2.3,1.2,11.3,243.4,90.0,23.1,15.6,15.017000
190,383,Taurean,Prince,6,8,6.666667,F,220,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,19.3,3.2,5.9,0.542,1.7,3.7,0.459,0.6,0.7,0.857,0.5,2.5,3.0,1.2,0.2,0.4,2.5,1.0,8.7,243.4,90.0,23.1,15.6,15.704876
194,393,Austin,Rivers,6,4,6.333333,G,200,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,2.9,0.0,0.4,0.000,0.0,0.1,0.000,0.0,0.0,0.000,0.0,0.2,0.2,0.1,0.0,0.0,0.0,0.0,0.0,243.4,90.0,23.1,15.6,5.800148
201,405,D'Angelo,Russell,6,5,6.416667,G,198,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,29.6,4.9,12.8,0.383,1.5,5.4,0.278,2.1,2.8,0.750,1.1,3.2,4.3,5.4,0.6,1.4,2.0,3.0,13.4,243.4,90.0,23.1,15.6,24.196413
218,447,Karl-Anthony,Towns,7,0,7.000000,C,248,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,35.0,7.9,16.2,0.488,2.3,6.3,0.365,3.9,4.4,0.886,2.1,6.5,8.6,5.5,0.6,0.6,3.8,3.2,22.0,243.4,90.0,23.1,15.6,25.634332
307,3153,Anthony,Edwards,6,4,6.330000,G,225,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,36.2,8.2,17.5,0.468,2.7,7.3,0.364,2.8,4.3,0.656,0.5,5.3,5.8,3.9,0.3,1.1,3.0,2.9,21.9,243.4,90.0,23.1,15.6,25.895095
308,3154,Jaden,McDaniels,6,9,6.750000,F,185,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,29.9,4.3,8.1,0.537,0.9,2.7,0.341,1.5,2.1,0.742,1.6,2.1,3.7,1.2,1.3,1.2,3.8,1.5,11.1,243.4,90.0,23.1,15.6,14.800851
309,3155,Jordan,McLaughlin,5,11,5.920000,G,185,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,15.8,1.5,3.5,0.413,0.2,1.7,0.136,0.5,0.5,1.000,0.3,1.5,1.8,3.8,0.1,0.8,0.5,0.6,3.6,243.4,90.0,23.1,15.6,11.497508
310,3156,Jaylen,Nowell,6,4,6.330000,G,201,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,17.4,4.0,9.9,0.403,1.1,3.9,0.293,1.0,1.3,0.789,0.5,2.1,2.7,2.1,0.1,0.5,1.4,0.9,10.1,243.4,90.0,23.1,15.6,27.483032
311,3157,Naz,Reid,6,9,6.750000,C,264,18,MIN,Minnesota,West,Northwest,Minnesota Timberwolves,Timberwolves,12.0,3.1,5.3,0.585,0.6,2.0,0.300,0.8,1.2,0.667,0.6,1.9,2.5,0.4,0.7,0.4,1.7,0.7,7.6,243.4,90.0,23.1,15.6,22.875782

Note: Jaylen Nowell and Naz Reid have abnormally high usage rates.

In [ ]:
thunder = appended_data[appended_data["team.abbreviation"] == "OKC"]

In [ ]:
thunder

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
78,175,Shai,Gilgeous-Alexander,6,6,6.500000,G,181,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,31.433333,10.11,18.89,0.535,0.78,2.56,0.304,6.11,6.33,0.965,0.78,3.00,3.78,5.33,1.00,2.00,2.11,2.89,27.11,248.65,96.84,19.25,14.16,32.530404
165,337,Mike,Muscala,6,11,6.916667,F-C,240,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,12.100000,2.11,4.67,0.452,0.67,2.67,0.250,1.22,1.56,0.786,0.67,3.56,4.22,0.56,0.22,0.00,1.33,0.44,6.11,248.65,96.84,19.25,14.16,19.940341
235,480,Kenrich,Williams,6,7,6.583333,G-F,210,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,18.216667,2.22,4.78,0.465,0.56,1.78,0.313,0.22,0.56,0.400,1.67,2.11,3.78,1.33,0.22,0.56,1.78,0.33,5.22,248.65,96.84,19.25,14.16,12.239500
312,3158,Josh,Giddey,6,8,6.670000,G,205,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,29.500000,6.30,13.70,0.457,1.10,3.40,0.317,0.90,1.30,0.733,1.30,5.90,7.20,5.30,0.50,0.40,2.30,3.50,14.50,248.65,96.84,19.25,14.16,25.076902
313,3159,Jalen,Williams,6,6,6.500000,F,195,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,23.300000,3.70,7.10,0.526,0.60,2.30,0.280,0.50,0.50,0.833,0.50,2.20,2.70,2.70,0.40,0.80,2.50,1.50,8.50,248.65,96.84,19.25,14.16,15.756954
314,3160,Lugentz,Dort,6,4,6.330000,F,215,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,30.800000,5.00,12.50,0.399,1.60,5.70,0.282,2.60,3.50,0.750,1.40,2.80,4.20,2.30,0.30,1.30,3.30,1.10,14.20,248.65,96.84,19.25,14.16,20.461372
315,3161,Aleksej,Pokusevski,7,0,7.000000,F,190,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,23.600000,3.90,8.30,0.472,1.40,3.50,0.391,0.50,1.00,0.538,1.60,3.90,5.50,1.70,1.80,0.80,1.80,1.60,9.80,248.65,96.84,19.25,14.16,18.237619
316,3162,Tre,Mann,6,3,6.250000,G,178,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,24.100000,4.20,10.50,0.401,1.80,5.50,0.333,0.80,1.20,0.625,0.80,2.30,3.10,2.20,0.10,0.90,1.80,1.00,11.10,248.65,96.84,19.25,14.16,20.774758
317,3163,Aaron,Wiggins,6,5,6.420000,G,190,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,21.300000,2.20,4.80,0.448,0.70,1.80,0.381,0.90,1.20,0.786,0.80,3.10,3.90,1.80,0.30,0.50,1.80,0.80,5.90,248.65,96.84,19.25,14.16,11.975640
318,3164,Darius,Bazley,6,9,6.750000,F,208,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,16.700000,2.50,5.80,0.422,0.60,1.60,0.389,0.50,1.00,0.455,1.60,3.10,4.70,1.50,1.30,0.80,1.50,0.50,6.00,248.65,96.84,19.25,14.16,16.799758
319,3165,Jeremiah,Robinson-Earl,6,8,6.670000,F,242,21,OKC,Oklahoma City,West,Northwest,Oklahoma City Thunder,Thunder,17.600000,3.00,5.80,0.519,1.30,2.90,0.439,0.70,1.10,0.667,1.10,2.90,4.00,0.70,0.30,0.80,1.90,0.50,8.00,248.65,96.84,19.25,14.16,16.044743

Note: Nothing unusual for the Thunder with regards to usage rate.

In [ ]:
blazers = appended_data[appended_data["team.abbreviation"] == "POR"]

In [ ]:
blazers

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
67,147,Drew,Eubanks,6,10,6.833333,F,245,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,14.550000,2.00,3.00,0.667,0.00,0.00,0.000,1.22,1.67,0.733,1.22,1.44,2.67,0.67,0.56,0.22,1.78,0.78,5.22,238.283333,79.42,26.24,15.69,13.864861
83,182,Jerami,Grant,6,9,6.750000,F,220,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,34.666667,5.56,12.00,0.463,1.67,4.22,0.395,5.11,6.78,0.754,0.56,3.44,4.00,2.67,0.78,0.44,1.78,2.22,17.89,238.283333,79.42,26.24,15.69,22.173648
96,202,Josh,Hart,6,5,6.416667,G,215,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,36.000000,3.11,6.78,0.459,0.56,1.33,0.417,2.00,2.56,0.783,1.89,6.67,8.56,4.67,0.22,1.11,2.44,1.78,8.78,238.283333,79.42,26.24,15.69,12.022642
138,278,Damian,Lillard,6,3,6.250000,G,195,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,19.433333,5.33,10.78,0.495,2.22,5.67,0.392,4.33,4.67,0.929,0.67,2.00,2.67,2.56,0.22,0.44,0.78,2.11,17.22,238.283333,79.42,26.24,15.69,34.362346
172,349,Jusuf,Nurkic,7,0,7.000000,C,275,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,29.550000,5.22,10.56,0.495,0.67,1.11,0.600,2.89,3.33,0.867,3.33,7.89,11.22,2.44,0.89,0.78,3.11,2.56,14.00,238.283333,79.42,26.24,15.69,22.054383
209,419,Anfernee,Simons,6,4,6.333333,G,185,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,28.666667,6.11,14.00,0.437,2.89,7.78,0.371,2.00,2.22,0.900,0.33,1.89,2.22,3.00,0.22,0.67,2.11,2.22,17.11,238.283333,79.42,26.24,15.69,26.804669
236,485,Justise,Winslow,6,7,6.583333,F,225,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,22.216667,2.56,7.00,0.365,0.44,1.44,0.308,0.78,1.11,0.700,1.67,2.89,4.56,3.22,0.56,1.44,2.11,1.22,6.33,238.283333,79.42,26.24,15.69,17.514570
320,3166,Nassir,Little,6,5,6.420000,F,220,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,15.000000,2.30,4.60,0.493,0.90,2.10,0.406,0.70,1.10,0.688,0.30,2.30,2.50,0.90,0.20,0.30,0.70,0.70,6.10,238.283333,79.42,26.24,15.69,17.229673
321,3167,Shaedon,Sharpe,6,6,6.500000,G,200,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,21.000000,4.00,7.20,0.554,1.30,2.50,0.514,0.80,1.10,0.733,0.80,1.70,2.50,0.40,0.30,0.30,2.00,0.80,10.10,238.283333,79.42,26.24,15.69,18.051835
322,3168,Trendon,Watford,6,8,6.670000,F,237,25,POR,Portland,West,Northwest,Portland Trail Blazers,Trail Blazers,17.200000,1.70,3.50,0.476,0.00,0.70,0.000,1.50,1.70,0.900,0.50,2.50,3.00,2.30,0.00,1.00,2.50,1.30,4.80,238.283333,79.42,26.24,15.69,14.412788

Note: Nothing unusual for the Trailblazers with regard to usage rate.

In [ ]:
jazz = appended_data[appended_data["team.abbreviation"] == "UTA"]

In [ ]:
jazz

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
18,38,Malik,Beasley,6,5,6.416667,G,195,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,24.4,3.9,9.9,0.394,2.2,5.7,0.386,0.7,0.8,0.875,0.8,2.2,3.0,1.1,0.2,1.1,0.7,0.5,10.7,232.9,88.7,20.5,14.5,18.290629
44,100,Jordan,Clarkson,6,5,6.416667,G,194,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,30.9,6.4,15.3,0.418,2.9,8.0,0.363,1.7,2.4,0.708,1.4,3.4,4.8,5.3,0.6,0.4,2.3,2.3,17.4,232.9,88.7,20.5,14.5,25.060474
47,104,Mike,Conley,6,1,6.083333,G,175,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,27.6,3.5,8.7,0.402,2.1,5.1,0.412,1.6,2.1,0.762,0.4,1.5,1.9,6.7,0.4,1.1,1.6,1.5,10.7,232.9,88.7,20.5,14.5,16.729429
75,171,Rudy,Gay,6,8,6.666667,F,230,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,10.7,1.2,3.3,0.364,0.5,1.7,0.294,0.2,0.4,0.500,0.4,1.8,2.2,0.9,0.4,0.3,1.1,0.6,3.1,232.9,88.7,20.5,14.5,15.811738
146,297,Lauri,Markkanen,7,0,7.000000,F,240,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,33.8,8.4,16.3,0.515,2.0,6.7,0.299,3.4,4.0,0.850,2.2,7.1,9.3,2.7,0.9,0.7,1.8,1.8,22.2,232.9,88.7,20.5,14.5,24.388875
176,358,Kelly,Olynyk,7,0,7.000000,F,240,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,27.1,4.6,8.2,0.561,1.9,3.2,0.594,1.6,2.4,0.667,1.4,2.7,4.1,3.4,0.6,1.5,4.6,2.5,12.7,232.9,88.7,20.5,14.5,18.006094
205,413,Collin,Sexton,6,2,6.166667,G,190,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,21.8,4.6,9.7,0.474,1.3,3.3,0.394,3.1,3.7,0.838,1.2,1.7,2.9,1.9,0.1,0.8,2.4,1.7,13.6,232.9,88.7,20.5,14.5,24.805642
222,457,Jarred,Vanderbilt,6,9,6.750000,F,214,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,25.3,3.7,6.6,0.561,0.6,1.1,0.545,1.0,1.5,0.667,2.2,6.0,8.2,3.1,0.5,1.5,4.0,1.9,9.0,232.9,88.7,20.5,14.5,15.028103
323,3169,Talen,Horton-Tucker,6,4,6.330000,G,234,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,16.4,2.9,7.2,40.000,0.8,2.9,0.255,1.4,1.8,0.821,0.6,2.1,2.7,2.6,0.3,0.8,1.4,1.0,7.9,232.9,88.7,20.5,14.5,22.758397
324,3170,Walker,Kessler,7,1,7.080000,C,245,29,UTA,Utah,West,Northwest,Utah Jazz,Jazz,14.9,2.5,3.5,0.696,0.0,0.0,0.000,0.7,1.4,0.500,2.3,3.1,5.4,0.7,1.6,0.2,1.8,0.7,5.6,232.9,88.7,20.5,14.5,13.416197

Note: Nothing unusual for the Jazz with regard to usage rate.

In [ ]:
warriors = appended_data[appended_data["team.abbreviation"] == "GSW"]

In [ ]:
warriors

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
53,115,Stephen,Curry,6,3,6.250000,G,190,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,31.3,9.1,18.7,0.487,4.6,11.1,0.414,5.1,5.4,0.944,0.8,5.5,6.3,6.1,0.1,1.1,1.9,2.6,27.9,234.5,87.3,18.0,15.0,32.186698
61,131,Donte,DiVincenzo,6,4,6.333333,G,203,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,4.3,0.5,1.1,0.455,0.2,0.6,0.333,0.3,0.4,0.750,0.0,0.2,0.2,0.3,0.0,0.1,0.4,0.6,1.5,234.5,87.3,18.0,15.0,18.564225
85,185,Draymond,Green,6,7,6.583333,F,230,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,26.2,3.5,5.7,0.614,0.3,1.0,0.300,0.7,1.2,0.583,0.7,4.6,5.3,5.0,0.6,1.0,3.4,2.2,8.0,234.5,87.3,18.0,15.0,13.687864
86,187,JaMychal,Green,6,9,6.750000,F,227,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,17.1,1.9,4.4,0.432,0.4,1.7,0.235,0.4,0.5,0.800,2.1,2.7,4.8,0.6,0.6,0.9,2.1,1.0,4.6,234.5,87.3,18.0,15.0,13.984683
139,282,Kevon,Looney,6,9,6.750000,F,220,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,23.7,3.0,4.6,0.652,0.0,0.0,0.000,0.8,1.3,0.615,2.1,3.9,6.0,3.2,0.2,0.3,3.1,0.2,6.8,234.5,87.3,18.0,15.0,9.644953
217,443,Klay,Thompson,6,7,6.583333,G,215,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,21.5,4.4,12.1,0.364,2.5,7.6,0.329,0.7,0.8,0.875,0.2,2.1,2.3,2.0,0.2,0.3,1.2,1.2,12.0,234.5,87.3,18.0,15.0,27.019061
233,475,Andrew,Wiggins,6,8,6.666667,F-G,194,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,30.0,6.0,12.9,0.465,2.1,5.4,0.389,1.6,2.2,0.727,1.6,3.5,5.1,2.6,1.1,1.1,2.7,0.8,15.7,234.5,87.3,18.0,15.0,20.804730
325,3171,Jordan,Poole,6,4,6.330000,G,194,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,28.5,5.4,12.7,0.426,2.3,6.7,0.337,3.0,3.6,0.833,0.3,1.5,1.8,4.5,0.2,1.1,2.3,2.9,16.1,234.5,87.3,18.0,15.0,25.656171
326,3172,Moses,Moody,6,6,6.500000,G,205,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,16.8,2.0,4.9,0.406,1.1,3.1,0.350,1.0,1.2,0.813,0.4,1.7,2.1,0.7,0.4,0.5,1.0,1.2,6.1,234.5,87.3,18.0,15.0,16.787486
327,3173,Anthony,Lamb,6,6,6.500000,G,227,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,21.0,3.4,5.9,0.585,1.9,3.7,0.500,0.0,0.0,0.000,0.9,2.9,3.7,1.6,0.0,0.9,2.3,1.1,8.7,234.5,87.3,18.0,15.0,14.183754
328,3174,Jonathan,Kuminga,6,8,6.670000,F,210,10,GSW,Golden State,West,Pacific,Golden State Warriors,Warriors,14.1,1.8,4.3,0.426,0.4,1.4,0.267,1.2,1.4,0.867,0.5,1.3,1.8,0.7,0.3,0.3,1.8,1.2,5.2,234.5,87.3,18.0,15.0,18.456987

Note: Nothing unusual for the Warriors with regard to usage rate.

In [ ]:
clippers = appended_data[appended_data["team.abbreviation"] == "LAC"]

In [ ]:
clippers

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
16,33,Nicolas,Batum,6,8,6.666667,F-G,200,13,LAC,LA,West,Pacific,LA Clippers,Clippers,17.433333,1.44,3.22,0.448,0.78,2.22,0.350,0.56,0.78,0.714,0.67,2.56,3.22,1.44,0.89,0.56,2.78,0.78,4.22,244.466667,84.68,19.8,15.63,11.172874
49,108,Robert,Covington,6,9,6.750000,F,225,13,LAC,LA,West,Pacific,LA Clippers,Clippers,9.666667,0.89,2.11,0.421,0.44,1.44,0.308,0.67,0.67,1.000,0.11,2.44,2.56,0.78,0.56,0.33,1.33,0.33,2.89,244.466667,84.68,19.8,15.63,12.687742
76,172,Paul,George,6,9,6.750000,F,220,13,LAC,LA,West,Pacific,LA Clippers,Clippers,31.216667,7.78,16.44,0.473,2.44,6.67,0.367,3.44,3.89,0.886,0.56,4.78,5.33,4.22,0.33,1.67,2.11,3.44,21.44,244.466667,84.68,19.8,15.63,31.019429
117,236,Reggie,Jackson,6,3,6.250000,G,208,13,LAC,LA,West,Pacific,LA Clippers,Clippers,29.766667,3.78,10.44,0.362,1.11,4.33,0.256,1.33,1.44,0.923,0.33,2.00,2.33,4.22,0.11,0.67,1.11,1.67,10.00,244.466667,84.68,19.8,15.63,19.199832
127,254,Luke,Kennard,6,5,6.416667,G,206,13,LAC,LA,West,Pacific,LA Clippers,Clippers,22.883333,3.11,6.22,0.500,1.56,3.33,0.467,0.22,0.22,1.000,0.44,3.22,3.67,0.56,0.00,0.33,1.56,1.22,8.00,244.466667,84.68,19.8,15.63,14.770772
136,274,Kawhi,Leonard,6,7,6.583333,F,230,13,LAC,LA,West,Pacific,LA Clippers,Clippers,4.666667,0.89,2.00,0.444,0.11,0.67,0.167,0.89,1.00,0.889,0.44,1.00,1.44,0.44,0.00,0.33,0.56,0.44,2.78,244.466667,84.68,19.8,15.63,27.677140
160,328,Marcus,Morris,6,9,6.750000,F,235,13,LAC,LA,West,Pacific,LA Clippers,Clippers,23.216667,4.44,9.00,0.494,1.44,3.78,0.382,0.44,0.44,1.000,0.44,4.22,4.67,2.00,0.11,0.78,1.89,0.67,10.78,244.466667,84.68,19.8,15.63,19.053339
189,380,Norman,Powell,6,4,6.333333,F-G,215,13,LAC,LA,West,Pacific,LA Clippers,Clippers,25.433333,4.11,10.11,0.407,1.11,4.00,0.278,1.56,2.33,0.667,0.56,2.89,3.44,1.33,0.33,0.56,1.44,2.44,10.89,244.466667,84.68,19.8,15.63,23.937481
228,467,John,Wall,6,4,6.333333,G,210,13,LAC,LA,West,Pacific,LA Clippers,Clippers,16.550000,3.89,8.56,0.455,0.67,2.67,0.250,1.56,2.56,0.609,0.33,1.33,1.67,3.67,0.22,0.67,1.22,1.22,10.00,244.466667,84.68,19.8,15.63,29.554181
241,493,Ivica,Zubac,7,1,7.083333,C,240,13,LAC,LA,West,Pacific,LA Clippers,Clippers,29.433333,4.22,6.78,0.623,0.00,0.11,0.000,1.56,2.67,0.583,2.44,9.11,11.56,1.44,2.78,0.33,3.00,2.22,10.00,244.466667,84.68,19.8,15.63,15.503221
329,3175,Moses,Brown,7,2,7.170000,C,245,13,LAC,Los Angeles,West,Pacific,Los Angeles Clippers,Clippers,4.100000,1.30,1.70,0.800,0.00,0.00,0.000,0.40,0.80,0.571,0.70,1.00,1.70,0.00,0.40,0.00,0.60,0.10,3.10,244.466667,84.68,19.8,15.63,23.539320
330,3176,Terrance,Mann,6,5,6.420000,G,215,13,LAC,Los Angeles,West,Pacific,Los Angeles Clippers,Clippers,17.900000,2.70,4.60,0.581,0.30,1.50,0.208,0.80,1.20,0.684,0.60,2.40,2.90,1.40,0.30,0.40,1.70,0.80,6.50,244.466667,84.68,19.8,15.63,14.852196
331,3177,Brandon,Boston Jr.,6,6,6.500000,G,188,13,LAC,Los Angeles,West,Pacific,Los Angeles Clippers,Clippers,3.200000,1.00,2.00,0.500,0.40,0.60,0.667,0.20,0.40,0.500,0.20,0.20,0.40,0.00,0.00,0.00,0.20,0.00,2.60,244.466667,84.68,19.8,15.63,30.496108
332,3178,Amir,Coffey,6,7,6.580000,G,210,13,LAC,Los Angeles,West,Pacific,Los Angeles Clippers,Clippers,9.000000,0.50,1.50,0.316,0.10,0.30,0.250,1.20,1.40,0.833,0.20,0.50,0.70,0.60,0.10,0.20,0.90,0.30,2.20,244.466667,84.68,19.8,15.63,12.038986

Note: Brandon Boston Jr. has an abnormally high usage rate.

In [ ]:
lakers = appended_data[appended_data["team.abbreviation"] == "LAL"]

In [ ]:
lakers

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
20,45,Patrick,Beverley,6,1,6.083333,G,185,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,27.866667,1.25,4.13,0.303,0.63,2.75,0.227,1.50,1.50,1.000,1.00,3.00,4.00,2.63,0.50,1.13,2.88,1.00,4.63,238.866667,88.67,23.89,13.85,8.781712
31,68,Troy,Brown Jr.,6,7,6.583333,F,215,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,19.616667,2.63,6.25,0.420,0.88,2.88,0.304,1.00,1.00,1.000,0.75,3.63,4.38,0.75,0.00,0.50,1.63,0.88,7.13,238.866667,88.67,23.89,13.85,16.310089
54,117,Anthony,Davis,6,10,6.833333,F-C,253,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,31.000000,8.25,15.75,0.524,0.38,1.63,0.231,3.25,4.00,0.813,2.75,6.88,9.63,2.00,2.00,1.50,2.38,1.13,20.13,238.866667,88.67,23.89,13.85,25.413816
73,166,Wenyen,Gabriel,6,9,6.750000,F,205,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,8.500000,1.13,2.00,0.563,0.00,0.38,0.000,0.63,1.00,0.625,0.63,1.50,2.13,0.50,0.25,0.50,1.25,0.38,2.88,238.866667,88.67,23.89,13.85,14.022190
118,237,LeBron,James,6,8,6.666667,F,250,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,36.366667,9.38,21.63,0.434,1.50,7.25,0.207,3.75,5.13,0.732,1.75,7.38,9.13,7.50,0.88,1.13,2.25,3.75,24.00,238.866667,88.67,23.89,13.85,32.120050
122,248,Damian,Jones,7,0,7.000000,C,245,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,6.500000,0.63,1.63,0.385,0.00,0.13,0.000,0.38,0.75,0.500,0.75,1.13,1.88,0.38,0.38,0.00,0.88,0.38,1.63,238.866667,88.67,23.89,13.85,15.215568
227,464,Lonnie,Walker IV,6,5,6.416667,G,205,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,32.000000,6.00,13.50,0.444,1.75,5.50,0.318,2.50,3.13,0.800,0.63,2.38,3.00,2.13,0.88,1.13,1.88,1.25,16.25,238.866667,88.67,23.89,13.85,21.300739
231,472,Russell,Westbrook,6,3,6.250000,G,200,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,25.616667,4.75,11.38,0.418,1.00,3.63,0.276,3.00,3.88,0.774,0.88,4.88,5.75,4.88,0.25,1.13,1.88,2.88,13.50,238.866667,88.67,23.89,13.85,26.344613
333,3179,Austin,Reaves,6,5,6.420000,G,197,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,26.900000,2.60,5.50,0.479,1.00,2.80,0.361,2.20,2.50,0.879,0.70,2.50,3.20,1.60,0.30,0.50,1.20,1.10,8.50,238.866667,88.67,23.89,13.85,12.098293
334,3180,Juan,Toscano-Anderson,6,6,6.500000,F,209,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,12.300000,1.00,2.50,0.400,0.20,1.10,0.182,0.40,0.50,0.800,0.10,2.00,2.10,0.50,0.30,0.30,1.70,0.80,2.60,238.866667,88.67,23.89,13.85,12.095483
335,3181,Matt,Ryan,6,7,6.580000,F,215,14,LAL,Los Angeles,West,Pacific,Los Angeles Lakers,Lakers,12.200000,1.50,4.40,0.341,1.30,3.10,0.419,0.40,0.50,0.800,0.20,1.10,1.30,0.30,0.00,0.20,1.40,0.30,4.70,238.866667,88.67,23.89,13.85,17.044762

Note: Nothing unusual about the Lakers with regard to usage rate.

In [ ]:
suns = appended_data[appended_data["team.abbreviation"] == "PHX"]

In [ ]:
suns

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
9,22,Deandre,Ayton,7,1,7.083333,C,250,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,19.550000,5.22,9.11,0.573,0.33,0.67,0.500,1.22,1.67,0.733,1.78,4.33,6.11,1.33,0.44,0.33,3.00,2.00,12.00,217.266667,76.91,21.79,12.34,26.636789
22,48,Bismack,Biyombo,6,9,6.750000,C,255,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,11.216667,1.33,2.33,0.571,0.00,0.00,0.000,0.56,0.89,0.625,0.67,2.56,3.22,0.44,1.78,0.00,1.67,0.67,3.22,217.266667,76.91,21.79,12.34,13.293573
25,57,Devin,Booker,6,6,6.500000,G,210,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,35.550000,9.67,20.00,0.483,2.22,6.33,0.351,5.44,6.22,0.875,0.67,3.22,3.89,5.11,0.56,0.89,2.33,2.67,27.00,217.266667,76.91,21.79,12.34,31.420368
28,61,Mikal,Bridges,6,7,6.583333,F,210,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,35.000000,5.56,9.22,0.602,1.11,2.22,0.500,2.67,3.11,0.857,1.33,3.56,4.89,2.89,1.11,0.89,2.33,1.22,14.89,217.266667,76.91,21.79,12.34,14.832827
50,110,Torrey,Craig,6,7,6.583333,F,215,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,16.333333,2.22,4.00,0.556,1.00,2.44,0.409,0.22,0.44,0.500,1.44,2.56,4.00,1.44,0.44,0.33,1.78,0.44,5.67,217.266667,76.91,21.79,12.34,12.472245
134,272,Damion,Lee,6,6,6.500000,G,210,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,18.100000,1.89,4.78,0.395,1.33,2.89,0.462,1.11,1.33,0.833,0.56,1.89,2.44,1.00,0.00,0.44,1.44,0.33,6.22,217.266667,76.91,21.79,12.34,13.833476
174,356,Josh,Okogie,6,4,6.333333,G,212,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,5.000000,0.44,1.11,0.400,0.00,0.44,0.000,0.44,0.67,0.667,0.33,1.00,1.33,0.00,0.11,0.33,0.67,0.44,1.33,217.266667,76.91,21.79,12.34,16.221096
179,367,Chris,Paul,6,0,6.000000,G,175,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,32.000000,3.00,8.33,0.360,1.00,3.67,0.273,3.33,3.78,0.882,0.56,4.22,4.78,10.22,0.22,1.67,2.44,1.44,10.33,217.266667,76.91,21.79,12.34,15.707922
180,368,Cameron,Payne,6,1,6.080000,G,183,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,12.550000,2.67,6.33,0.421,1.00,2.56,0.391,0.56,0.67,0.833,0.22,1.33,1.56,2.22,0.11,0.89,0.78,1.44,6.89,217.266667,76.91,21.79,12.34,28.252103
203,407,Dario,Saric,6,10,6.833333,F,223,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,4.100000,0.56,1.67,0.333,0.22,0.67,0.333,0.00,0.11,0.000,0.67,0.89,1.56,0.33,0.00,0.33,0.56,0.33,1.33,217.266667,76.91,21.79,12.34,21.965031
206,414,Landry,Shamet,6,5,6.416667,G,188,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,12.766667,1.67,4.33,0.385,1.11,3.00,0.370,0.78,1.00,0.778,0.22,0.44,0.67,1.00,0.11,0.56,1.00,0.56,5.22,217.266667,76.91,21.79,12.34,18.354840
336,3183,Jock,Landale,6,11,6.920000,C,255,24,PHX,Phoenix,West,Pacific,Phoenix Suns,Suns,15.100000,2.90,5.70,0.500,0.20,1.80,0.120,1.40,1.90,0.769,1.70,2.60,4.40,0.80,0.90,0.40,2.60,0.80,7.40,217.266667,76.91,21.79,12.34,21.359116

Note: Cameron Payne has an abnormally high usage rate, but keep in mind he has been getting extensive minutes in the wake of Chris Paul's abscense.

In [ ]:
kings = appended_data[appended_data["team.abbreviation"] == "SAC"]

In [ ]:
kings

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
13,30,Harrison,Barnes,6,8,6.666667,F,225,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,33.250000,3.50,9.00,0.389,0.63,3.38,0.185,3.50,4.38,0.800,1.13,4.50,5.63,2.13,0.13,0.50,1.38,1.13,11.13,241.85,87.42,22.94,14.55,15.651874
56,123,Matthew,Dellavedova,6,4,6.333333,G,200,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,3.616667,0.38,0.88,0.429,0.25,0.38,0.667,0.00,0.00,0.000,0.13,0.13,0.25,0.50,0.00,0.13,0.63,0.25,1.00,241.85,87.42,22.94,14.55,13.485948
71,161,De'Aaron,Fox,6,3,6.250000,G,175,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,27.866667,8.88,16.00,0.555,1.75,4.75,0.368,3.50,4.00,0.875,0.63,4.50,5.13,4.00,0.50,0.75,2.88,3.38,23.00,241.85,87.42,22.94,14.55,32.743981
106,217,Richaun,Holmes,6,10,6.833333,F-C,235,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,12.500000,1.75,2.50,0.700,0.00,0.00,0.000,0.50,0.75,0.667,1.00,1.88,2.88,0.00,0.13,0.25,1.88,0.63,4.00,241.85,87.42,22.94,14.55,11.947516
108,221,Kevin,Huerter,6,7,6.583333,G,190,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,31.866667,5.88,11.75,0.500,4.00,7.75,0.516,1.88,2.63,0.714,0.00,2.63,2.63,3.63,0.25,0.50,2.25,1.00,17.63,241.85,87.42,22.94,14.55,18.837123
135,273,Alex,Len,7,1,7.083333,C,250,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,1.000000,0.00,0.13,0.000,0.00,0.00,0.000,0.13,0.25,0.500,0.00,0.25,0.25,0.00,0.00,0.00,0.25,0.00,0.13,241.85,87.42,22.94,14.55,10.359118
144,290,Trey,Lyles,6,10,6.833333,F,234,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,12.616667,1.75,4.38,0.400,1.25,3.25,0.385,0.50,0.88,0.571,0.38,2.25,2.63,0.88,0.50,0.50,1.13,0.88,5.25,241.85,87.42,22.94,14.55,19.319686
154,314,Chimezie,Metu,6,10,6.833333,F,225,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,4.616667,0.50,1.25,0.400,0.00,0.38,0.000,0.50,0.50,1.000,0.00,1.25,1.25,0.50,0.13,0.13,0.38,0.00,1.50,241.85,87.42,22.94,14.55,13.743595
159,324,Malik,Monk,6,3,6.250000,G,200,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,19.866667,3.75,9.00,0.417,2.13,5.88,0.362,0.88,1.00,0.875,0.50,1.63,2.13,4.38,0.38,0.50,1.50,1.63,10.50,241.85,87.42,22.94,14.55,24.051055
202,406,Domantas,Sabonis,6,11,6.916667,F,240,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,31.250000,6.00,10.63,0.565,0.13,1.13,0.111,3.88,6.25,0.620,2.25,8.38,10.63,6.13,0.75,0.88,4.25,2.25,16.00,241.85,87.42,22.94,14.55,21.588401
337,3184,Keegan,Murray,6,8,6.670000,F,215,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,30.300000,4.60,10.20,0.450,2.30,6.00,0.375,0.60,0.80,0.778,0.70,3.00,3.70,1.10,0.80,1.00,2.30,1.60,12.00,241.85,87.42,22.94,14.55,17.310781
338,3185,Davion,Mitchell,6,0,6.000000,G,202,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,19.300000,2.80,5.90,0.476,0.90,2.80,0.333,0.30,0.40,0.667,0.10,1.20,1.30,2.00,0.10,0.40,1.60,1.20,6.80,241.85,87.42,22.94,14.55,16.272223
339,3186,Terrence,Davis,6,4,6.330000,G,201,26,SAC,Sacramento,West,Pacific,Sacramento Kings,Kings,13.800000,2.80,5.80,0.487,1.50,3.80,0.408,0.90,1.10,0.857,0.50,2.50,3.00,1.60,0.20,0.80,1.80,0.60,8.20,241.85,87.42,22.94,14.55,21.531451

Note: Nothing unusual for the Kings with regard to usage rate.

In [ ]:
mavericks = appended_data[appended_data["team.abbreviation"] == "DAL"]

In [ ]:
mavericks

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
36,75,Reggie,Bullock,6,7,6.583333,G-F,205,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,31.500000,2.00,5.88,0.340,1.63,4.75,0.342,0.38,0.63,0.600,0.63,2.38,3.00,1.00,0.25,1.13,3.00,0.88,6.00,246.083333,82.18,29.65,12.73,10.184853
60,130,Spencer,Dinwiddie,6,6,6.500000,G,210,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,32.750000,6.63,13.75,0.482,2.75,6.50,0.423,1.25,1.75,0.714,0.13,2.50,2.63,4.25,0.00,1.38,2.75,1.63,17.25,246.083333,82.18,29.65,12.73,22.481570
62,132,Luka,Doncic,6,7,6.583333,F-G,218,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,36.500000,12.38,23.50,0.527,2.13,8.13,0.262,9.13,11.63,0.785,1.13,7.63,8.75,8.63,0.50,1.88,3.25,3.38,36.00,246.083333,82.18,29.65,12.73,39.965433
68,158,Dorian,Finney-Smith,6,8,6.666667,F,220,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,32.616667,3.13,7.13,0.439,1.38,4.50,0.306,0.25,0.63,0.400,1.63,2.63,4.25,0.63,0.63,0.88,2.50,0.88,7.88,246.083333,82.18,29.65,12.73,11.583336
89,191,Tim,Hardaway Jr.,6,6,6.500000,G,205,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,21.250000,2.75,9.00,0.306,1.75,5.38,0.326,2.88,3.00,0.958,0.00,1.50,1.50,1.63,0.25,0.50,1.50,1.00,10.13,246.083333,82.18,29.65,12.73,24.285827
128,257,Maxi,Kleber,6,11,6.916667,F,240,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,25.500000,1.50,3.88,0.387,0.75,2.50,0.300,1.13,1.50,0.750,0.88,3.25,4.13,0.88,0.88,0.50,1.63,1.00,4.88,246.083333,82.18,29.65,12.73,9.904556
151,306,JaVale,McGee,7,0,7.000000,C,270,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,9.000000,1.63,2.88,0.565,0.00,0.00,0.000,1.00,1.63,0.615,0.88,1.75,2.63,0.25,0.50,0.38,0.88,0.88,4.25,246.083333,82.18,29.65,12.73,22.679287
181,370,Theo,Pinson,6,6,6.500000,G-F,218,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,3.300000,0.30,0.30,1.000,0.00,0.00,0.000,0.50,0.50,1.000,0.00,0.80,0.80,0.30,0.00,0.00,0.30,0.00,1.00,246.083333,82.18,29.65,12.73,7.183810
188,379,Dwight,Powell,6,11,6.916667,F-C,240,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,10.366667,1.75,2.63,0.667,0.00,0.13,0.000,1.13,1.50,0.750,0.63,1.00,1.63,0.25,0.38,0.13,1.13,0.13,4.63,246.083333,82.18,29.65,12.73,15.040157
237,486,Christian,Wood,6,10,6.833333,F,214,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,25.000000,6.00,10.13,0.593,1.50,3.13,0.480,3.25,4.88,0.667,1.38,6.63,8.00,0.75,0.63,0.25,2.50,2.25,16.75,246.083333,82.18,29.65,12.73,26.491547
340,3187,Josh,Green,6,5,6.420000,G,200,7,DAL,Dallas,West,Southwest,Dallas Mavericks,Mavericks,18.300000,1.80,3.10,0.581,0.80,1.70,0.458,1.30,2.00,0.643,1.00,1.40,2.40,0.80,0.10,1.10,2.00,0.70,5.60,246.083333,82.18,29.65,12.73,11.658970

Note: Nothing unusual for the Mavs with regard to usage rate.

In [ ]:
rockets = appended_data[appended_data["team.abbreviation"] == "HOU"]

In [ ]:
rockets

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
81,178,Eric,Gordon,6,4,6.333333,G,215,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,24.9,3.5,7.8,0.449,1.4,4.0,0.350,1.4,1.8,0.778,0.2,1.5,1.7,2.6,0.4,0.7,0.7,1.7,9.8,253.3,93.7,26.3,18.0,16.986393
145,296,Boban,Marjanovic,7,3,7.250000,C,290,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,1.2,0.1,0.3,0.333,0.0,0.0,0.000,0.3,0.5,0.600,0.1,0.3,0.4,0.1,0.0,0.1,0.1,0.1,0.5,253.3,93.7,26.3,18.0,21.232992
341,3188,Kevin,Porter Jr.,6,4,6.330000,G,203,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,34.9,6.5,15.9,0.410,1.8,5.3,0.338,4.2,5.7,0.733,1.5,4.7,6.1,5.8,0.5,1.3,2.9,4.0,19.1,253.3,93.7,26.3,18.0,26.386295
342,3189,Jalen,Green,6,4,6.330000,G,186,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,34.5,7.7,17.9,0.428,2.9,7.7,0.371,3.5,4.3,0.800,0.6,3.7,4.3,3.3,0.3,0.7,1.5,2.9,21.7,253.3,93.7,26.3,18.0,27.030521
343,3190,Jabari,Smith Jr.,6,11,6.920000,F,220,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,29.6,3.3,10.4,0.315,1.7,5.6,0.304,1.8,2.1,0.833,1.4,5.4,6.9,0.8,1.1,0.4,3.6,1.1,10.1,253.3,93.7,26.3,18.0,17.249260
344,3191,Alperen,Sengun,6,11,6.920000,C,243,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,26.5,5.8,10.2,0.568,0.2,1.2,0.200,4.2,5.3,0.783,3.5,5.0,8.5,1.8,1.2,0.6,3.4,2.2,15.9,253.3,93.7,26.3,18.0,22.846337
345,3192,Garrison,Matthews,6,6,6.500000,G,215,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,11.8,1.1,3.2,0.333,1.1,3.2,0.341,0.6,0.6,1.000,0.1,0.8,0.8,0.4,0.1,0.3,1.2,0.4,3.8,253.3,93.7,26.3,18.0,13.457236
346,3193,Jae'Sean,Tate,6,5,6.420000,F,230,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,22.7,3.3,6.7,0.500,0.7,1.7,0.400,1.0,1.3,0.750,2.7,1.7,4.3,3.3,0.0,1.0,5.0,1.7,8.3,253.3,93.7,26.3,18.0,16.242922
347,3194,Kenyon,Martin Jr.,6,7,6.580000,F,215,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,25.1,4.2,7.9,0.529,1.1,3.3,0.340,1.4,2.1,0.677,1.2,3.5,4.7,1.5,0.7,0.4,2.0,1.2,10.9,253.3,93.7,26.3,18.0,16.412248
348,3195,Usman,Garuba,6,8,6.667000,F,229,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,15.8,1.8,2.8,0.622,0.5,0.5,0.857,0.5,1.0,0.462,2.2,3.5,5.7,1.3,0.8,0.8,1.9,1.1,4.5,253.3,93.7,26.3,18.0,11.288426
349,3196,Josh,Christopher,6,4,6.330000,G,215,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,8.2,1.3,3.4,0.378,0.3,1.3,0.214,0.1,0.2,0.500,0.4,1.1,1.5,0.6,0.0,0.3,0.9,0.7,2.9,253.3,93.7,26.3,18.0,20.989088
350,3197,Tari,Eason,6,8,6.670000,F,215,11,HOU,Houston,West,Southwest,Houston Rockets,Rockets,18.1,3.2,7.2,0.444,0.8,1.9,0.414,1.1,1.4,0.810,2.1,2.9,4.9,1.1,0.5,1.5,2.3,0.9,8.3,253.3,93.7,26.3,18.0,19.789708

Note: Boban has an abnormally high usage rate, but this is because he is very efficient in the minutes he is given.

In [ ]:
grizzlies = appended_data[appended_data["team.abbreviation"] == "MEM"]

In [ ]:
grizzlies

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
0,3,Steven,Adams,7,0,7.000000,C,265,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,26.100000,3.11,5.33,0.583,0.00,0.00,0.000,0.78,2.56,0.304,4.67,6.44,11.11,2.56,1.56,0.78,2.44,2.11,7.00,246.566667,96.39,25.22,15.32,13.179526
30,66,Dillon,Brooks,6,6,6.500000,G-F,220,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,17.766667,3.89,8.89,0.438,1.89,3.78,0.500,1.00,1.56,0.643,0.22,1.33,1.56,1.33,0.00,0.44,2.00,0.89,10.67,246.566667,96.39,25.22,15.32,23.655565
123,249,Tyus,Jones,6,2,6.166667,G,196,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,24.000000,4.89,10.67,0.458,1.56,4.44,0.350,0.44,1.00,0.444,0.33,1.67,2.00,4.22,0.11,0.67,0.67,1.22,11.78,246.566667,96.39,25.22,15.32,20.629741
351,3198,Ja,Morant,6,3,6.250000,G,174,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,33.200000,10.30,21.50,0.480,2.10,5.20,0.403,6.60,8.50,0.782,1.20,4.90,6.20,6.80,0.30,1.20,1.80,3.90,29.30,246.566667,96.39,25.22,15.32,35.244667
352,3199,Desmond,Bane,6,5,6.420000,G,215,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,33.500000,8.30,17.80,0.465,3.80,8.50,0.451,4.30,4.80,0.912,0.50,4.40,4.90,4.80,0.30,0.60,2.40,2.30,24.70,246.566667,96.39,25.22,15.32,26.624705
353,3200,John,Konchar,6,5,6.420000,G,210,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,26.600000,2.70,5.90,0.458,1.40,3.60,0.392,0.10,0.10,0.500,1.50,4.20,5.70,1.10,0.30,1.00,1.80,0.50,6.90,246.566667,96.39,25.22,15.32,9.727827
354,3201,Santi,Aldama,6,11,6.920000,F,215,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,27.500000,3.70,8.00,0.467,1.20,3.60,0.333,1.00,1.60,0.625,1.80,4.50,6.30,0.90,1.10,0.90,2.80,0.70,9.70,246.566667,96.39,25.22,15.32,13.731623
355,3202,Brandon,Clarke,6,8,6.670000,F,215,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,19.100000,4.00,6.50,0.619,0.10,0.40,0.167,1.90,2.60,0.744,1.10,3.30,4.50,1.50,1.00,0.30,2.50,1.30,10.00,246.566667,96.39,25.22,15.32,18.803572
356,3203,Kennedy,Chandler,6,0,6.000000,G,171,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,9.700000,1.00,3.20,0.316,0.20,1.00,0.167,0.20,0.70,0.250,0.20,0.80,1.00,2.00,0.30,0.30,0.50,1.00,2.30,246.566667,96.39,25.22,15.32,18.661825
357,3204,David,Roddy,6,5,6.420000,G,252,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,17.700000,2.10,5.70,0.372,0.80,3.10,0.261,0.50,0.70,0.700,0.80,1.80,2.60,0.70,0.30,0.50,1.50,0.50,5.50,246.566667,96.39,25.22,15.32,14.764414
358,3205,Xavier,Tillman,6,8,6.670000,C,245,15,MEM,Memphis,West,Southwest,Memphis Grizzlies,Grizzlies,11.400000,1.50,2.90,0.522,0.10,0.50,0.250,0.40,1.10,0.333,1.40,1.50,2.90,0.80,0.30,0.00,1.00,0.90,3.50,246.566667,96.39,25.22,15.32,15.089907

Note: Nothing unusual for the Grizzlies with regard to usage rate.

In [ ]:
pelicans = appended_data[appended_data["team.abbreviation"] == "NOP"]

In [ ]:
pelicans

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
82,180,Devonte',Graham,6,2,6.166667,G,185,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,17.550000,1.56,4.11,0.378,1.33,3.22,0.414,0.56,0.89,0.625,0.11,1.22,1.33,2.56,0.11,0.44,1.11,0.67,5.00,271.083333,99.52,27.2,14.1,12.721329
100,207,Willy,Hernangomez,6,11,6.916667,C,240,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,1.550000,0.11,0.56,0.200,0.00,0.11,0.000,0.22,0.22,1.000,0.44,0.56,1.00,0.11,0.00,0.00,0.22,0.11,0.44,271.083333,99.52,27.2,14.1,21.356746
112,227,Brandon,Ingram,6,9,6.750000,F,190,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,17.000000,4.11,8.67,0.474,1.00,2.00,0.500,2.78,3.56,0.781,0.11,2.89,3.00,2.67,0.56,0.44,1.00,1.67,12.00,271.083333,99.52,27.2,14.1,30.235435
148,303,CJ,McCollum,6,3,6.250000,G,190,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,35.883333,8.67,20.33,0.426,2.22,6.89,0.323,2.00,2.33,0.857,0.89,4.44,5.33,6.22,0.44,1.33,2.11,1.78,21.56,271.083333,99.52,27.2,14.1,27.833329
167,340,Larry,Nance Jr.,6,9,6.750000,F,230,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,23.666667,4.56,6.89,0.661,0.22,0.56,0.400,0.33,0.56,0.600,1.44,4.00,5.44,2.44,0.67,1.11,2.22,1.11,9.67,271.083333,99.52,27.2,14.1,15.042221
215,436,Garrett,Temple,6,6,6.500000,G-F,195,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,2.333333,0.22,0.44,0.500,0.22,0.44,0.500,0.00,0.00,0.000,0.00,0.11,0.11,0.11,0.00,0.11,0.22,0.00,0.67,271.083333,99.52,27.2,14.1,8.140678
221,455,Jonas,Valanciunas,7,0,7.000000,C,265,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,25.000000,5.11,10.22,0.500,0.44,1.33,0.333,3.78,4.44,0.850,3.78,6.89,10.67,2.22,0.44,0.56,2.11,1.56,14.44,271.083333,99.52,27.2,14.1,23.715324
359,3206,Herbert,Jones,6,7,6.580000,F,206,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,29.400000,3.60,7.70,0.471,0.50,2.10,0.261,2.50,3.40,0.757,1.50,2.10,3.50,2.10,0.50,1.00,3.70,0.90,10.40,271.083333,99.52,27.2,14.1,14.824726
360,3207,Zion,Williamson,6,6,6.500000,F,284,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,32.200000,9.00,15.90,0.566,0.30,0.50,0.500,5.30,7.40,0.716,2.10,4.30,6.40,3.90,0.30,1.10,2.70,2.70,23.50,271.083333,99.52,27.2,14.1,29.302149
361,3208,Jose,Alvarado,6,0,6.000000,G,179,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,19.100000,3.30,6.60,0.495,1.30,3.30,0.400,0.50,0.70,0.700,0.40,1.70,2.10,2.90,0.20,0.80,2.10,1.30,8.30,271.083333,99.52,27.2,14.1,18.551911
362,3209,Trey,Murphy III,6,8,6.670000,G,206,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,28.100000,4.10,8.50,0.488,2.40,5.50,0.434,1.40,1.50,0.955,1.20,3.50,4.70,1.30,0.50,1.10,1.70,0.70,12.10,271.083333,99.52,27.2,14.1,15.147999
363,3210,Naji,Marshall,6,7,6.580000,F,220,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,20.000000,2.40,5.90,0.409,0.70,2.20,0.333,0.90,1.30,0.737,0.90,2.20,3.10,1.50,0.20,0.60,1.30,1.00,6.50,271.083333,99.52,27.2,14.1,16.128409
364,3211,Jaxon,Hayes,6,11,6.920000,C,220,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,7.400000,0.20,1.00,0.200,0.00,0.40,0.000,0.00,0.00,0.000,0.20,0.80,1.00,0.60,0.20,0.20,1.00,0.20,0.40,271.083333,99.52,27.2,14.1,7.000583
365,3212,Dyson,Daniels,6,6,6.500000,G,199,19,NOP,New Orleans,West,Southwest,New Orleans Pelicans,Pelicans,11.900000,1.40,2.70,0.526,0.60,1.10,0.500,0.60,0.90,0.667,0.70,2.70,3.40,1.30,0.60,0.60,1.40,0.40,4.00,271.083333,99.52,27.2,14.1,12.682624

Note: Willy Hernangomez has an abnormally high usage rate.

In [ ]:
spurs = appended_data[appended_data["team.abbreviation"] == "SAS"]

In [ ]:
spurs

,id,first_name,last_name,height_feet,height_inches,actual_height_ft,position,weight_pounds,team.id,team.abbreviation,team.city,team.conference,team.division,team.full_name,team.name,mpg,fgm,fga,fg_pct,fg3m,fg3a,fg3_pct,ftm,fta,ft_pct,oreb,dreb,reb,ast,blk,stl,pf,turnover,pts,TmMP,TmFGA,TmFTA,TmTOV,usage
15,32,Keita,Bates-Diop,6,9,6.750000,F,229,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,13.4,2.9,5.4,0.537,0.4,1.2,0.333,1.6,1.9,0.842,0.9,1.2,2.1,0.5,0.0,0.4,0.5,1.2,7.8,239.5,91.9,20.3,16.8,22.596679
46,102,Zach,Collins,7,0,7.000000,F-C,235,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,15.8,3.1,5.9,0.525,0.7,1.8,0.389,0.6,0.9,0.667,1.2,3.0,4.2,2.5,1.1,0.7,2.7,1.7,7.5,239.5,91.9,20.3,16.8,20.607520
59,129,Gorgui,Dieng,6,11,6.916667,C,252,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,5.5,0.8,1.7,0.471,0.5,1.4,0.357,0.0,0.0,0.000,0.4,0.8,1.2,1.1,0.4,0.1,0.9,0.7,2.1,239.5,91.9,20.3,16.8,17.768820
150,305,Doug,McDermott,6,8,6.666667,F,225,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,20.5,3.7,8.4,0.440,2.2,5.1,0.431,0.6,0.9,0.667,0.3,1.8,2.1,1.5,0.2,0.0,1.6,1.0,10.2,239.5,91.9,20.3,16.8,19.458302
183,373,Jakob,Poeltl,7,0,7.000000,C,230,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,28.3,5.3,8.6,0.616,0.0,0.0,0.000,1.7,3.3,0.515,4.0,6.0,10.0,3.3,0.9,0.9,2.0,2.3,12.3,239.5,91.9,20.3,16.8,17.773006
193,391,Josh,Richardson,6,6,6.500000,G-F,200,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,20.6,3.0,7.0,0.429,1.8,4.3,0.419,1.5,1.8,0.833,0.1,1.9,2.0,3.1,0.1,0.6,2.0,1.5,9.3,239.5,91.9,20.3,16.8,18.367583
366,3213,Tre,Jones,6,1,6.080000,G,185,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,29.9,4.3,10.5,0.414,0.9,2.3,0.412,2.2,2.4,0.917,0.6,2.9,3.5,6.7,0.2,1.5,2.1,1.9,11.8,239.5,91.9,20.3,16.8,18.325457
367,3214,Devin,Vassell,6,5,6.420000,G,200,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,31.8,7.6,16.2,0.469,3.2,7.5,0.422,2.1,2.8,0.758,0.1,3.8,3.8,3.3,0.5,0.8,1.3,1.6,20.4,239.5,91.9,20.3,16.8,24.370663
368,3215,Keldon,Johnson,6,5,6.420000,F,220,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,32.9,7.6,16.9,0.451,3.7,8.8,0.423,3.7,4.8,0.776,0.6,4.4,4.9,3.6,0.1,1.0,1.5,2.9,22.7,239.5,91.9,20.3,16.8,27.120404
369,3216,Jeremy,Sochan,6,8,6.670000,F,220,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,24.5,3.3,6.9,0.485,0.4,2.3,0.171,0.6,0.9,0.692,1.0,3.0,4.0,1.9,0.5,0.8,2.6,1.3,7.7,239.5,91.9,20.3,16.8,14.286977
370,3217,Romeo,Langford,6,5,6.420000,G,215,27,SAS,San Antonio,West,Southwest,San Antonio Spurs,Spurs,16.3,1.9,4.4,0.419,0.1,1.0,0.143,0.4,0.6,0.750,1.4,0.6,2.0,0.4,0.3,0.4,1.4,0.7,4.3,239.5,91.9,20.3,16.8,13.400197

Note: Nothing unusual for the Spurs with regard to usage rate.

In [ ]:
appended_data["usage"].mean()

18.68585097954166

In [ ]:
appended_data["usage"].min()

0.0

In [ ]:
appended_data["usage"].max()

39.72109942633022

In [ ]:
appended_data["usage"].nlargest(10)

62     39.721099
5      37.504922
240    35.798669
351    35.244667
66     34.659545
138    34.362346
65     33.078748
71     32.743981
78     32.530404
53     32.186698
Name: usage, dtype: float64

In [ ]:
appended_data.loc[62]

id                                132
first_name                       Luka
last_name                      Doncic
height_feet                         6
height_inches                       7
actual_height_ft             6.583333
position                          F-G
weight_pounds                     218
team.id                             7
team.abbreviation                 DAL
team.city                      Dallas
team.conference                  West
team.division               Southwest
team.full_name       Dallas Mavericks
team.name                   Mavericks
mpg                              36.5
fgm                             12.38
fga                              23.5
fg_pct                          0.527
fg3m                             2.13
fg3a                             8.13
fg3_pct                         0.262
ftm                              9.13
fta                             11.63
ft_pct                          0.785
oreb                             1.13
dreb                             7.63
reb                              8.75
ast                              8.63
blk                               0.5
stl                              1.88
pf                               3.25
turnover                         3.38
pts                              36.0
TmMP                           243.65
TmFGA                           81.88
TmFTA                            29.4
TmTOV                           12.73
usage                       39.721099
Name: 62, dtype: object

In [ ]:
appended_data.loc[5]

id                                15
first_name                   Giannis
last_name              Antetokounmpo
height_feet                        6
height_inches                     11
actual_height_ft            6.916667
position                           F
weight_pounds                    242
team.id                           17
team.abbreviation                MIL
team.city                  Milwaukee
team.conference                 East
team.division                Central
team.full_name       Milwaukee Bucks
team.name                      Bucks
mpg                        29.666667
fgm                            10.44
fga                            18.89
fg_pct                         0.553
fg3m                            0.89
fg3a                            3.22
fg3_pct                        0.276
ftm                             7.22
fta                            11.44
ft_pct                         0.631
oreb                            1.78
dreb                            9.56
reb                            11.33
ast                             5.11
blk                             1.33
stl                             0.89
pf                              2.56
turnover                        2.78
pts                             29.0
TmMP                      233.633333
TmFGA                          88.68
TmFTA                          24.26
TmTOV                          12.79
usage                      37.504922
Name: 5, dtype: object

In [ ]:
appended_data.loc[240]

id                             490
first_name                    Trae
last_name                    Young
height_feet                      6
height_inches                    2
actual_height_ft          6.166667
position                         G
weight_pounds                  180
team.id                          1
team.abbreviation              ATL
team.city                  Atlanta
team.conference               East
team.division            Southeast
team.full_name       Atlanta Hawks
team.name                    Hawks
mpg                           35.1
fgm                           8.67
fga                          22.78
fg_pct                        0.38
fg3m                          2.44
fg3a                           8.0
fg3_pct                      0.306
ftm                           8.44
fta                           9.22
ft_pct                       0.916
oreb                          0.89
dreb                          2.44
reb                           3.33
ast                           9.44
blk                           0.22
stl                           0.67
pf                            1.78
turnover                      3.33
pts                          28.22
TmMP                    218.616667
TmFGA                        85.21
TmFTA                        19.07
TmTOV                        11.37
usage                    35.798669
Name: 240, dtype: object

In [ ]:
appended_data.loc[351]

id                                3198
first_name                          Ja
last_name                       Morant
height_feet                          6
height_inches                        3
actual_height_ft                  6.25
position                             G
weight_pounds                      174
team.id                             15
team.abbreviation                  MEM
team.city                      Memphis
team.conference                   West
team.division                Southwest
team.full_name       Memphis Grizzlies
team.name                    Grizzlies
mpg                               33.2
fgm                               10.3
fga                               21.5
fg_pct                            0.48
fg3m                               2.1
fg3a                               5.2
fg3_pct                          0.403
ftm                                6.6
fta                                8.5
ft_pct                           0.782
oreb                               1.2
dreb                               4.9
reb                                6.2
ast                                6.8
blk                                0.3
stl                                1.2
pf                                 1.8
turnover                           3.9
pts                               29.3
TmMP                        246.566667
TmFGA                            96.39
TmFTA                            25.22
TmTOV                            15.32
usage                        35.244667
Name: 351, dtype: object

In [ ]:
appended_data.loc[66]

id                                  145
first_name                         Joel
last_name                        Embiid
height_feet                           7
height_inches                         0
actual_height_ft                    7.0
position                            F-C
weight_pounds                       250
team.id                              23
team.abbreviation                   PHI
team.city                  Philadelphia
team.conference                    East
team.division                  Atlantic
team.full_name       Philadelphia 76ers
team.name                         76ers
mpg                                20.7
fgm                                 5.8
fga                                10.9
fg_pct                            0.532
fg3m                                0.6
fg3a                                2.0
fg3_pct                             0.3
ftm                                 4.1
fta                                 5.2
ft_pct                            0.788
oreb                                0.8
dreb                                4.9
reb                                 5.7
ast                                 2.0
blk                                 0.7
stl                                 0.3
pf                                  1.9
turnover                            2.2
pts                                16.3
TmMP                              245.7
TmFGA                              83.9
TmFTA                              20.9
TmTOV                              12.3
usage                         34.659545
Name: 66, dtype: object

In [ ]:
appended_data.loc[138]

id                                      278
first_name                           Damian
last_name                           Lillard
height_feet                               6
height_inches                             3
actual_height_ft                       6.25
position                                  G
weight_pounds                           195
team.id                                  25
team.abbreviation                       POR
team.city                          Portland
team.conference                        West
team.division                     Northwest
team.full_name       Portland Trail Blazers
team.name                     Trail Blazers
mpg                               19.433333
fgm                                    5.33
fga                                   10.78
fg_pct                                0.495
fg3m                                   2.22
fg3a                                   5.67
fg3_pct                               0.392
ftm                                    4.33
fta                                    4.67
ft_pct                                0.929
oreb                                   0.67
dreb                                    2.0
reb                                    2.67
ast                                    2.56
blk                                    0.22
stl                                    0.44
pf                                     0.78
turnover                               2.11
pts                                   17.22
TmMP                             238.283333
TmFGA                                 79.42
TmFTA                                 26.24
TmTOV                                 15.69
usage                             34.362346
Name: 138, dtype: object

In [ ]:
appended_data.loc[65]

id                             140
first_name                   Kevin
last_name                   Durant
height_feet                      6
height_inches                    9
actual_height_ft              6.75
position                         F
weight_pounds                  240
team.id                          3
team.abbreviation              BKN
team.city                 Brooklyn
team.conference               East
team.division             Atlantic
team.full_name       Brooklyn Nets
team.name                     Nets
mpg                           37.2
fgm                           10.5
fga                           20.3
fg_pct                       0.517
fg3m                           1.7
fg3a                           5.1
fg3_pct                      0.333
ftm                            8.8
fta                            9.3
ft_pct                       0.946
oreb                           0.4
dreb                           5.8
reb                            6.2
ast                            4.8
blk                            2.0
stl                            0.8
pf                             2.3
turnover                       3.5
pts                           31.5
TmMP                         237.6
TmFGA                         84.1
TmFTA                         24.8
TmTOV                         12.7
usage                    33.078748
Name: 65, dtype: object

In [ ]:
appended_data.loc[71]

id                                161
first_name                   De'Aaron
last_name                         Fox
height_feet                         6
height_inches                       3
actual_height_ft                 6.25
position                            G
weight_pounds                     175
team.id                            26
team.abbreviation                 SAC
team.city                  Sacramento
team.conference                  West
team.division                 Pacific
team.full_name       Sacramento Kings
team.name                       Kings
mpg                         27.866667
fgm                              8.88
fga                              16.0
fg_pct                          0.555
fg3m                             1.75
fg3a                             4.75
fg3_pct                         0.368
ftm                               3.5
fta                               4.0
ft_pct                          0.875
oreb                             0.63
dreb                              4.5
reb                              5.13
ast                               4.0
blk                               0.5
stl                              0.75
pf                               2.88
turnover                         3.38
pts                              23.0
TmMP                           241.85
TmFGA                           87.42
TmFTA                           22.94
TmTOV                           14.55
usage                       32.743981
Name: 71, dtype: object

In [ ]:
appended_data.loc[78]

id                                     175
first_name                            Shai
last_name               Gilgeous-Alexander
height_feet                              6
height_inches                            6
actual_height_ft                       6.5
position                                 G
weight_pounds                          181
team.id                                 21
team.abbreviation                      OKC
team.city                    Oklahoma City
team.conference                       West
team.division                    Northwest
team.full_name       Oklahoma City Thunder
team.name                          Thunder
mpg                              31.433333
fgm                                  10.11
fga                                  18.89
fg_pct                               0.535
fg3m                                  0.78
fg3a                                  2.56
fg3_pct                              0.304
ftm                                   6.11
fta                                   6.33
ft_pct                               0.965
oreb                                  0.78
dreb                                   3.0
reb                                   3.78
ast                                   5.33
blk                                    1.0
stl                                    2.0
pf                                    2.11
turnover                              2.89
pts                                  27.11
TmMP                                248.65
TmFGA                                96.84
TmFTA                                19.25
TmTOV                                14.16
usage                            32.530404
Name: 78, dtype: object

In [ ]:
appended_data.loc[53]

id                                     115
first_name                         Stephen
last_name                            Curry
height_feet                              6
height_inches                            3
actual_height_ft                      6.25
position                                 G
weight_pounds                          190
team.id                                 10
team.abbreviation                      GSW
team.city                     Golden State
team.conference                       West
team.division                      Pacific
team.full_name       Golden State Warriors
team.name                         Warriors
mpg                                   31.3
fgm                                    9.1
fga                                   18.7
fg_pct                               0.487
fg3m                                   4.6
fg3a                                  11.1
fg3_pct                              0.414
ftm                                    5.1
fta                                    5.4
ft_pct                               0.944
oreb                                   0.8
dreb                                   5.5
reb                                    6.3
ast                                    6.1
blk                                    0.1
stl                                    1.1
pf                                     1.9
turnover                               2.6
pts                                   27.9
TmMP                                 234.5
TmFGA                                 87.3
TmFTA                                 18.0
TmTOV                                 15.0
usage                            32.186698
Name: 53, dtype: object

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

df = pd.read_excel('nba_analysis.xlsx')

def locate_1():
    print('Please enter your team of Five!: \n')
    
    t = True
    while t:
        a = input('Name of Point Guard: ')
        if a in list(df['Full_name']):
            t = False
            return a
        else:
            print('\n')
            print('Name not recognized, please try again.')


def locate_2():
    
    t = True
    while t:
        b = input('Name of Shooting Guard: ')
        if b in list(df['Full_name']):
            t = False
            return b
        else:
            print('\n')
            print('Name not recognized, please try again.')



def locate_3():
    
    t = True
    while t:
        a = input('Name of Small Forward: ')
        if a in list(df['Full_name']):
            t = False
            return a
        else:
            print('\n')
            print('Name not recognized, please try again.')
            
def locate_4():
    
    t = True
    while t:
        a = input('Name of Power Forward: ')
        if a in list(df['Full_name']):
            t = False
            return a
        else:
            print('\n')
            print('Name not recognized, please try again.')

def locate_5():
   
    t = True
    while t:
        a = input('Name of Center: ')
        if a in list(df['Full_name']):
            t = False
            return a
        else:
            print('\n')
            print('Name not recognized, please try again.')

def team_builder():
    a = locate_1()
    b = locate_2()
    c = locate_3()
    d = locate_4()
    e = locate_5()
    return [a,b,c,d,e]

def locater(a):
    appended_data = []
    for i in a:
        new_loc = df.loc[df['Full_name'] == i]
        #print(i)
        appended_data.append(new_loc)
    appended_data = pd.concat(appended_data)
    return appended_data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#builds team
nam = team_builder()

#creates df
t = locater(nam)

Please enter your team of Five!:

In [ ]:
t